"""Registry constants for validate_skill_gate."""

from __future__ import annotations

__all__ = [
    'ABSTRACT_HINT_TOKENS',
    'ABSTRACT_SURFACE_TOKENS',
    'CAPTION_HINT_TOKENS',
    'CONTENT_WRITING_HINT_TOKENS',
    'EVIDENCE_FIELD_TO_TYPE',
    'FORMAT_REPAIR_TASK_EXPLICIT_OR_NONE_PREFIXES',
    'FORMAT_REPAIR_TASK_EXPLICIT_REQUIRED_PREFIXES',
    'FORMAT_REPAIR_TASK_HELPER_LOCK_PREFIXES',
    'FORMAT_REPAIR_TASK_PATH_OPTIONAL_FILE_PREFIXES',
    'FORMAT_REPAIR_TASK_PATH_VALIDATION_PREFIXES',
    'FORMAT_REPAIR_TASK_SURFACE_DETECTOR_SPECS',
    'FORMAT_REPAIR_TASK_SURFACE_REQUIRED_PREFIXES',
    'FORMAT_REPAIR_TASK_TOUCH_CONTEXT_RAW_PREFIXES',
    'FORMULA_HINT_TOKENS',
    'GATE_SINGLE_PREFIX_POLICY',
    'HEADER_FOOTER_HINT_TOKENS',
    'NON_CONTENT_THESIS_HINT_TOKENS',
    'NUMBERING_PARAGRAPH_TOKENS',
    'PATH_FIELD_PREFIXES',
    'REQUIRED_NON_NONE_PATHS_BY_MODE',
    'REVIEW_EVIDENCE_ALWAYS_REQUIRED_PREFIXES',
    'REVIEW_EVIDENCE_MAYBE_NOT_APPLICABLE_PREFIXES',
    'REVIEW_EVIDENCE_OPTIONAL_STATUS_PREFIXES',
    'REVIEW_EVIDENCE_RENDERER_REQUIRED_PREFIXES',
    'REVIEW_EVIDENCE_RENDERER_REQUIRED_TYPES',
    'REVIEW_EVIDENCE_SURFACE_CONFIRM_PREFIXES',
    'REVIEW_EVIDENCE_SURFACE_DETECTOR_SPECS',
    'REVIEW_EVIDENCE_SURFACE_TEXT_PREFIXES',
    'RUNTIME_SCREENSHOT_HINT_TOKENS',
    'TABLE_HINT_TOKENS',
    'TAIL_BLOCK_HINT_TOKENS',
    'TOC_HINT_TOKENS',
]

ABSTRACT_HINT_TOKENS = (
    'abstract',
    '\u6458\u8981',
    'keyword',
    '\u5173\u952e\u8bcd',
    'front matter',
)

ABSTRACT_SURFACE_TOKENS = {
    'chinese abstract body',
    'chinese abstract title',
    'chinese keyword line',
    'english abstract body',
    'english abstract title',
    'english keyword line',
}

CAPTION_HINT_TOKENS = (
    'caption',
    'figure caption',
    'table caption',
    'table title',
    '\u56fe\u9898',
    '\u8868\u9898',
    '\u56fe\u6ce8',
    '\u8868\u6ce8',
)

CONTENT_WRITING_HINT_TOKENS = (
    'draft',
    'rewrite',
    'abstract',
    'chapter',
    'body',
    'content',
    'thesis selftest',
    'combo selftest',
    '\u6b63\u6587',
    '\u6458\u8981',
    '\u91cd\u5199',
    '\u64b0\u5199',
)

EVIDENCE_FIELD_TO_TYPE = {
    '- figure review evidence paths:': 'figure-review',
    '- paragraph-review evidence paths:': 'paragraph-review',
    '- program evidence paths:': 'program-review',
    '- table authority evidence paths:': 'thesis-rendered-page',
    '- table-local structure evidence paths:': 'thesis-rendered-page',
    '- table rendered baseline comparison evidence paths:': 'thesis-rendered-page',
    '- table title-mode evidence paths:': 'thesis-rendered-page',
    '- table header-bottom middle-rule evidence paths:': 'thesis-rendered-page',
    '- tail-block pagination evidence paths:': 'thesis-rendered-page',
    '- tail-block rendered opener comparison evidence paths:': 'touched-page-review',
    '- thesis rendered-page evidence paths:': 'thesis-rendered-page',
    '- toc rendered baseline comparison evidence paths:': 'thesis-rendered-page',
    '- toc restoration evidence paths:': 'thesis-rendered-page',
    '- toc visual geometry evidence paths:': 'thesis-rendered-page',
    '- toc paragraph-and-typography evidence paths:': 'thesis-rendered-page',
    '- toc visible-run typography evidence paths:': 'thesis-rendered-page',
    '- whole-document pagination evidence path:': 'thesis-rendered-page',
    '- touched-page review evidence paths:': 'touched-page-review',
    '- surface-face parity audit evidence path:': 'thesis-rendered-page',
    '- surface paragraph-and-typography audit evidence path:': 'thesis-rendered-page',
    '- sibling-surface audit evidence path:': 'thesis-rendered-page',
    '- font-family baseline audit evidence path:': 'thesis-rendered-page',
    '- active template profile evidence path:': 'thesis-rendered-page',
    '- cover style evidence path:': 'thesis-rendered-page',
    '- cover identity value-line evidence path:': 'thesis-rendered-page',
    '- declaration/title front matter evidence path:': 'thesis-rendered-page',
    '- Chinese abstract title evidence path:': 'thesis-rendered-page',
    '- Chinese abstract body evidence path:': 'thesis-rendered-page',
    '- Chinese keyword line evidence path:': 'thesis-rendered-page',
    '- English abstract title evidence path:': 'thesis-rendered-page',
    '- English abstract body evidence path:': 'thesis-rendered-page',
    '- English keyword line evidence path:': 'thesis-rendered-page',
    '- TOC title evidence path:': 'thesis-rendered-page',
    '- TOC entries evidence path:': 'thesis-rendered-page',
    '- TOC dotted leaders evidence path:': 'thesis-rendered-page',
    '- TOC page-number column evidence path:': 'thesis-rendered-page',
    '- body heading levels evidence path:': 'thesis-rendered-page',
    '- body citation superscripts evidence path:': 'thesis-rendered-page',
    '- review comments/change marks evidence path:': 'thesis-rendered-page',
    '- touched chapter rendered evidence paths:': 'touched-page-review',
    '- references title evidence path:': 'thesis-rendered-page',
    '- references entries evidence path:': 'thesis-rendered-page',
    '- rendered references-page evidence path:': 'thesis-rendered-page',
    '- acknowledgement title evidence path:': 'thesis-rendered-page',
    '- acknowledgement body evidence path:': 'thesis-rendered-page',
    '- header evidence path:': 'thesis-rendered-page',
    '- body opener/header title consistency evidence path:': 'thesis-rendered-page',
    '- footer evidence path:': 'thesis-rendered-page',
    '- page numbers evidence path:': 'thesis-rendered-page',
    '- user-reported visual defect render-geometry evidence path:': 'thesis-rendered-page',
    '- content mutation rendered-page review path:': 'thesis-rendered-page',
    '- touched-page/blast-radius machine-vision evidence paths:': 'touched-page-review',
}

FORMAT_REPAIR_TASK_EXPLICIT_OR_NONE_PREFIXES = [
    '- active table authority lock:',
    '- table authority source type:',
    '- table authority source file path:',
    '- table authority manuscript binding proof:',
    '- table authority rationale:',
    '- WPS table preset target:',
    '- TOC baseline-source lock:',
    '- TOC baseline source file path:',
    '- TOC implementation type in baseline source:',
    '- TOC restoration source allowed to be current working draft?:',
    '- TOC title visual metrics baseline:',
    '- TOC level-1 visual metrics baseline:',
    '- TOC level-2 visual metrics baseline:',
    '- TOC level-3 visual metrics baseline:',
    '- TOC title paragraph-dialog / typography metrics baseline:',
    '- TOC level-1 paragraph-dialog / typography metrics baseline:',
    '- TOC level-2 paragraph-dialog / typography metrics baseline:',
    '- TOC level-3 paragraph-dialog / typography metrics baseline:',
    '- TOC visible-run direct typography baseline:',
    '- TOC per-level text/tab/page-number run typography baseline:',
    '- TOC per-level style-binding baseline:',
    '- TOC scale/compression baseline verdict:',
    '- TOC page-count / occupancy baseline:',
    '- TOC visual geometry baseline:',
    '- TOC post-refresh restoration owner:',
    '- TOC repair included this round?:',
    '- live TOC required this round?:',
    '- whole-document pagination surface active?:',
    '- whole-document pagination baseline source:',
    '- package baseline manifest path:',
    '- pre-mutation page map path:',
    '- section break numbering baseline path:',
    '- page-number restart baseline path:',
    '- header/footer link-to-previous baseline path:',
    '- hard page-break / section-break baseline path:',
    '- field-refresh baseline state:',
    '- TOC-to-heading page sync baseline path:',
    '- logical-physical page map baseline path:',
    '- rendered page count baseline:',
    '- blank-page scan baseline path:',
    '- front-matter numbering convention expected on rendered pages:',
    '- office-app path used to verify adjusted page numbers:',
    '- abstract surfaces locked:',
    '- abstract baseline source file path:',
    '- Chinese abstract title baseline paragraph/run path:',
    '- Chinese abstract body baseline paragraph/run path:',
    '- Chinese keyword line baseline paragraph/run path:',
    '- English abstract title baseline paragraph/run path:',
    '- English abstract body baseline paragraph/run path:',
    '- English keyword line baseline paragraph/run path:',
    '- keyword label/content run-split baseline:',
    '- English abstract semantic parity baseline:',
    '- mandatory thesis surface inventory path:',
    '- thesis surface inventory status matrix:',
    '- front matter surface coverage matrix path:',
    '- end matter surface coverage matrix path:',
    '- high-risk thesis format surfaces required:',
    '- high-risk thesis format surface matrix path:',
    '- mandatory surface rows required:',
    '- cover style baseline source:',
    '- cover identity value-line baseline source:',
    '- reference-entry baseline source:',
    '- appendix baseline source or absence reason:',
    '- discovered candidate template paths:',
    '- candidate template selection reason:',
    '- caption baseline source file path:',
    '- caption wording lock:',
    '- table-local structure evidence record paths:',
    '- touched header/footer surfaces:',
    '- body-header ownership strategy:',
    '- tail-block ownership strategy:',
    '- footer baseline source file path:',
    '- footer/page-number presentation target:',
    '- logical-page to physical-rendered-page mapping method:',
    '- post-script smoke-audit rule active?:',
    '- runtime screenshot route-caption-asset map path:',
    '- template alignment verdict:',
    '- format preservation promise active?:',
    '- format preservation promise source:',
    '- format preservation promise verdict:',
    '- caption rendered review evidence record paths:',
    '- header/footer rendered review evidence record paths:',
    '- active table authority source summary:',
    '- table authority checkpoints:',
    '- table-local structure checkpoints:',
    '- rendered table baseline comparison evidence record paths:',
    '- TOC title baseline paragraph path:',
    '- TOC level-1 baseline paragraph path:',
    '- TOC level-2 baseline paragraph path:',
    '- TOC level-3 baseline paragraph path:',
    '- TOC level-4 baseline paragraph path:',
    '- TOC entries by used level baseline:',
    '- TOC right-tab position baseline:',
    '- TOC line-spacing baseline:',
    '- TOC paragraph before/after spacing baseline:',
    '- TOC line-spacing mode/value baseline:',
    '- TOC indentation chars/points baseline:',
    '- TOC per-level font-size/weight baseline:',
    '- TOC dotted-leader baseline:',
    '- TOC page-number column per-entry baseline:',
    '- TOC title bbox baseline:',
    '- TOC entry row bbox baseline:',
    '- TOC per-level left-indent x baseline:',
    '- TOC line-spacing y-delta baseline:',
    '- TOC dotted-leader start/end/density baseline:',
    '- TOC page-number x column baseline:',
    '- TOC row-count / page-occupancy rhythm baseline:',
    '- forbidden substitute evidence allowed?:',
    '- TOC restoration checkpoints:',
    '- TOC post-refresh restoration evidence record paths:',
    '- TOC rendered baseline comparison evidence record paths:',
    '- TOC visual geometry evidence record paths:',
    '- TOC paragraph-and-typography evidence record paths:',
    '- TOC visible-run typography evidence record paths:',
    '- whole-document pagination evidence record path:',
    '- package drift report path:',
    '- post-mutation page map path:',
    '- whole-document pagination diff path:',
    '- section break numbering map path:',
    '- chapter start owner map path:',
    '- tail-block owner map path:',
    '- TOC-to-heading page sync map path:',
    '- logical-physical page map path:',
    '- blank-page scan evidence path:',
    '- TOC used-level inventory checkpoints:',
    '- whole-document pagination checkpoints:',
    '- tail-block pagination repair included this round?:',
    '- tail-block titles in scope:',
    '- tail-block title baseline source file path:',
    '- references title baseline paragraph/run path:',
    '- references entries baseline paragraph/run path:',
    '- acknowledgement title baseline paragraph/run path:',
    '- acknowledgement body baseline paragraph/run path:',
    '- end-matter indentation detector required?:',
    '- tail-block opener ownership baseline:',
    '- tail-block pagination restoration owner:',
    '- tail-block opener page-occupancy baseline:',
    '- tail-block title baseline paragraph paths:',
    '- references title indentation baseline:',
    '- references entries left/hanging indentation baseline:',
    '- acknowledgement title indentation baseline:',
    '- acknowledgement body indentation baseline:',
    '- tail-block pagination checkpoints:',
    '- references title indentation checkpoints:',
    '- references entries indentation checkpoints:',
    '- acknowledgement title indentation checkpoints:',
    '- acknowledgement body indentation checkpoints:',
    '- end-matter rendered geometry checkpoints:',
    '- references title indentation evidence record path:',
    '- references entries indentation evidence record path:',
    '- acknowledgement title indentation evidence record path:',
    '- acknowledgement body indentation evidence record path:',
    '- tail-block pagination evidence record paths:',
    '- tail-block rendered opener comparison evidence record paths:',
    '- baseline promotion gate:',
    '- release blocker ledger path:',
    '- unresolved release blocker count:',
    '- scoped artifact next-baseline verdict:',
    '- blocker conditions:',
    '- contaminated intermediate source used?:',
    '- contaminated intermediate source disposition:',
    '- known caveats:',
]

FORMAT_REPAIR_TASK_EXPLICIT_REQUIRED_PREFIXES = [
    '- task mode:',
    '- content frozen?:',
    '- protected blocks:',
    '- touched blocks this round:',
    '- active references:',
    '- routed child files:',
    '- active checklist names:',
    '- thesis mutation transaction owner path:',
    '- selected mutation transaction workflow:',
    '- thesis mutation transaction record path:',
    '- transaction target surface ids:',
    '- transaction protected sibling surface ids:',
    '- transaction write owner:',
    '- transaction final docx path:',
    '- transaction final docx sha256:',
    '- protected-surface evidence contract path:',
    '- protected-surface evidence contract loaded?:',
    '- canonical protected surface id set:',
    '- protected-surface owner map:',
    '- protected-surface evidence map:',
    '- protected-surface reviewed output sha256:',
    '- protected-surface evidence contract verdict:',
    '- exact master manuscript path:',
    '- true current master manuscript:',
    '- exact review-copy path:',
    '- exact review-copy sha256 before mutation:',
    '- exact helper-script target path:',
    '- expected output path after helper script:',
    '- expected output sha256 after helper script:',
    '- helper scripts planned this round:',
    '- project-local helper script preflight summary:',
    '- project-local helper preflight report path:',
    '- project-local helper active run dir:',
    '- project-local helper risk count:',
    '- project-local helper scanner exit status:',
    '- project-local helper disposition:',
    '- canonical source restart required?:',
    '- source manuscript genealogy path:',
    '- source retention manifest path:',
    '- source retention ratio:',
    '- source retention verdict:',
    '- rebuild class:',
    '- clean-source restart source path:',
    '- contaminated-baseline disposition:',
    '- format preservation promise active?:',
    '- format preservation promise source:',
    '- format preservation promise verdict:',
    '- project template discovery root:',
    '- template discovery patterns:',
    '- active template source type:',
    '- active template path lock:',
    '- active template fingerprint:',
    '- active template profile path:',
    '- active template selected before mutation?:',
    '- template discovery report path:',
    '- template profile generation command:',
    '- template profile generated before mutation?:',
    '- locked path encoding verdict:',
    '- protected-surface write-owner map:',
    '- touched-surface page map:',
    '- stale audit map:',
    '- rerender target map:',
    '- mandatory thesis surface inventory path:',
    '- thesis surface inventory status matrix:',
    '- front matter surface coverage matrix path:',
    '- end matter surface coverage matrix path:',
    '- high-risk thesis format surfaces required:',
    '- high-risk thesis format surface matrix path:',
    '- mandatory surface rows required:',
    '- surfaces explicitly excluded from generic scripts:',
    '- custom-layout result tables locked this round:',
    '- template-owned surface families touched or user-reported:',
    '- surface-face parity baseline source paths:',
    '- surface-face parity owner map:',
    '- surface-face sibling audit scope:',
    '- all-surface paragraph-dialog / typography metrics baseline:',
    '- all-surface style-binding hard-field rule:',
    '- all-surface paragraph-dialog / typography evidence record paths:',
    '- font baseline source for each touched surface:',
    '- Chinese/East Asian font mapping baseline:',
    '- Western/English font mapping baseline:',
    '- complex-script font mapping baseline:',
    '- effective font chain baseline required?:',
    '- protected-surface effective font chain rule:',
    '- theme/default font alias policy:',
    '- heading / TOC / chapter-start linked lane active?:',
    '- paragraph-level rendered review path:',
    '- verified renderer executable path:',
    '- verified rasterizer executable path:',
    '- rendered page review evidence record paths:',
    '- thesis mutation transaction validator command:',
    '- thesis mutation transaction validator result:',
    '- paragraph-review evidence record paths:',
    '- touched-page review evidence record paths:',
    '- rendered PDF path:',
    '- page-image artifact paths:',
    '- output manuscript paths:',
    '- reviewed output sha256:',
    '- school template:',
    '- approved sample:',
    '- explicit user rule:',
    '- page-class sample comparison targets:',
    '- surface-face baseline paragraph/run paths:',
    '- surface-face baseline metrics recorded:',
    '- effective font resolver inputs:',
    '- rendered pages to inspect:',
    '- rendered sentinel texts to confirm:',
    '- specific format classes to verify:',
    '- surface-face parity checkpoints:',
    '- all-surface paragraph-dialog and typography checkpoints:',
    '- sibling-surface audit checkpoints:',
    '- font-family baseline checkpoints:',
    '- protected-surface effective font chain checkpoints:',
    '- builder/default font rejection checkpoints:',
    '- post-script smoke-audit checkpoints:',
    '- chapter-start pagination checkpoints:',
    '- chapter format preservation checkpoints:',
    '- review-copy promotion gate:',
    '- baseline promotion gate:',
    '- release blocker ledger path:',
    '- unresolved release blocker count:',
    '- scoped artifact next-baseline verdict:',
    '- format preservation blocker conditions:',
]

FORMAT_REPAIR_TASK_HELPER_LOCK_PREFIXES = [
    '- exact helper-script target path:',
    '- expected output path after helper script:',
    '- protected-surface write-owner map:',
    '- surfaces explicitly excluded from generic scripts:',
    '- custom-layout result tables locked this round:',
    '- post-script smoke-audit evidence path:',
    '- post-script smoke-audit checkpoints:',
]

FORMAT_REPAIR_TASK_PATH_OPTIONAL_FILE_PREFIXES = {
    '- approved sample:',
    '- exact master manuscript path:',
    '- exact review-copy path:',
    '- output manuscript paths:',
    '- project template discovery root:',
    '- protected-surface evidence contract path:',
    '- school template:',
    '- true current master manuscript:',
}

FORMAT_REPAIR_TASK_PATH_VALIDATION_PREFIXES = (
    '- exact master manuscript path:',
    '- true current master manuscript:',
    '- exact review-copy path:',
    '- project template discovery root:',
    '- discovered candidate template paths:',
    '- active template path lock:',
    '- active template profile path:',
    '- template discovery report path:',
    '- mandatory thesis surface inventory path:',
    '- front matter surface coverage matrix path:',
    '- end matter surface coverage matrix path:',
    '- high-risk thesis format surface matrix path:',
    '- protected surface contract evidence path:',
    '- table authority source file path:',
    '- TOC baseline source file path:',
    '- abstract baseline source file path:',
    '- caption baseline source file path:',
    '- verified renderer executable path:',
    '- verified rasterizer executable path:',
    '- footer baseline source file path:',
    '- rendered PDF path:',
    '- page-image artifact paths:',
    '- output manuscript paths:',
    '- school template:',
    '- approved sample:',
    '- rendered page review evidence record paths:',
    '- paragraph-review evidence record paths:',
    '- touched-page review evidence record paths:',
    '- chapter format diff path:',
    '- touched chapter rendered evidence paths:',
    '- all-surface paragraph-dialog / typography evidence record paths:',
    '- rendered table baseline comparison evidence record paths:',
    '- TOC post-refresh restoration evidence record paths:',
    '- TOC rendered baseline comparison evidence record paths:',
    '- TOC visual geometry evidence record paths:',
    '- TOC paragraph-and-typography evidence record paths:',
    '- TOC visible-run typography evidence record paths:',
    '- tail-block title baseline source file path:',
    '- tail-block pagination evidence record paths:',
    '- tail-block rendered opener comparison evidence record paths:',
    '- caption rendered review evidence record paths:',
    '- header/footer rendered review evidence record paths:',
    '- post-script smoke-audit evidence path:',
    '- project-local helper preflight report path:',
    '- source manuscript genealogy path:',
    '- source retention manifest path:',
    '- release blocker ledger path:',
)

FORMAT_REPAIR_TASK_SURFACE_DETECTOR_SPECS = {
    'abstract': {
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- TOC repair included this round?:',
            '- live TOC required this round?:',
            '- touched header/footer surfaces:',
            '- active table authority source summary:',
            '- tail-block pagination repair included this round?:',
            '- tail-block titles in scope:',
        ),
        'tokens': (
            'abstract',
            '\u6458\u8981',
            'keyword',
            '\u5173\u952e\u8bcd',
            'front matter',
        ),
    },
    'caption': {
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- TOC repair included this round?:',
            '- live TOC required this round?:',
            '- touched header/footer surfaces:',
            '- active table authority source summary:',
            '- tail-block pagination repair included this round?:',
            '- tail-block titles in scope:',
        ),
        'tokens': (
            'caption',
            'figure caption',
            'table caption',
            'table title',
            '\u56fe\u9898',
            '\u8868\u9898',
            '\u56fe\u6ce8',
            '\u8868\u6ce8',
        ),
    },
    'header_footer': {
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- TOC repair included this round?:',
            '- live TOC required this round?:',
            '- touched header/footer surfaces:',
            '- active table authority source summary:',
            '- tail-block pagination repair included this round?:',
            '- tail-block titles in scope:',
        ),
        'tokens': (
            'header',
            'footer',
            'page number',
            'header/footer',
            '\u9875\u7709',
            '\u9875\u811a',
            '\u9875\u7801',
        ),
    },
    'heading': {
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- TOC repair included this round?:',
            '- live TOC required this round?:',
            '- touched header/footer surfaces:',
            '- active table authority source summary:',
            '- tail-block pagination repair included this round?:',
            '- tail-block titles in scope:',
        ),
        'tokens': (
            'heading',
            'toc',
            'chapter',
            'title',
            '\u6807\u9898',
            '\u76ee\u5f55',
            '\u7ae0',
        ),
    },
    'style_blast_radius': {
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- helper scripts planned this round:',
            '- template-owned surface families touched or user-reported:',
            '- style-blast-radius trigger:',
            '- body-header ownership strategy:',
        ),
        'tokens': (
            'body style',
            'normal',
            'docdefaults',
            'theme font',
            'default paragraph',
            'paragraph spacing',
            'default spacing',
            'broad run',
            'broad paragraph',
            'style-blast-radius',
            'style blast radius',
            'toc style',
            'table style',
            'caption style',
            '\u6b63\u6587\u6837\u5f0f',
            '\u6837\u5f0f\u6a21\u677f',
            '\u6bb5\u8ddd',
            '\u76ee\u5f55\u6837\u5f0f',
            '\u8868\u683c\u6837\u5f0f',
        ),
    },
    'runtime_screenshot': {
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- TOC repair included this round?:',
            '- live TOC required this round?:',
            '- touched header/footer surfaces:',
            '- active table authority source summary:',
            '- tail-block pagination repair included this round?:',
            '- tail-block titles in scope:',
        ),
        'tokens': (
            'runtime screenshot',
            'screenshot',
            'chapter 4',
            '\u56fe4.',
            '\u8fd0\u884c\u622a\u56fe',
        ),
    },
    'table': {
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- active table authority source summary:',
            '- table authority checkpoints:',
        ),
        'tokens': (
            'table',
            'tables',
            'table family',
            'table style',
            'three-line table',
            'WPS preset',
            '\u8868',
            '\u8868\u683c',
            '\u4e09\u7ebf\u8868',
        ),
    },
    'tail_block': {
        'explicit_flag_prefix': '- tail-block pagination repair included this round?:',
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- touched header/footer surfaces:',
            '- tail-block ownership strategy:',
            '- tail-block pagination repair included this round?:',
            '- tail-block titles in scope:',
            '- tail-block pagination checkpoints:',
        ),
        'tokens': (
            'tail-block',
            'tail block',
            'end matter',
            'tail-block title indentation',
            'title indentation',
            'left indent',
            'hanging indent',
            'first-line indent',
            'rendered left-x',
            'centerline',
            'references',
            'bibliography',
            'acknowledgement',
            'acknowledgements',
            'acknowledgment',
            'acknowledgments',
            'conclusion',
            'appendix',
            '\u53c2\u8003\u6587\u732e',
            '\u81f4\u8c22',
            '\u7ed3\u8bba',
            '\u9644\u5f55',
        ),
    },
    'toc': {
        'explicit_flag_prefix': '- TOC repair included this round?:',
        'raw_prefixes': (
            '- touched blocks this round:',
            '- specific format classes to verify:',
            '- explicit user rule:',
            '- TOC repair included this round?:',
            '- live TOC required this round?:',
            '- touched header/footer surfaces:',
            '- TOC restoration checkpoints:',
        ),
        'tokens': (
            'toc',
            'table of contents',
            '\u76ee\u5f55',
        ),
    },
}

FORMAT_REPAIR_TASK_SURFACE_REQUIRED_PREFIXES = {
    'caption': {
        'message': 'format-repair task record must lock caption baseline and evidence when captions are touched',
        'prefixes': [
            '- caption baseline source file path:',
            '- caption wording lock:',
            '- caption rendered review evidence record paths:',
        ],
    },
    'header_footer': {
        'message': 'format-repair task record must lock header/footer baseline and evidence when header/footer is touched',
        'prefixes': [
            '- touched header/footer surfaces:',
            '- body-header ownership strategy:',
            '- tail-block ownership strategy:',
            '- footer baseline source file path:',
            '- footer/page-number presentation target:',
            '- logical-page to physical-rendered-page mapping method:',
            '- header/footer rendered review evidence record paths:',
        ],
    },
    'table': {
        'message': 'format-repair task record must lock table authority data when tables are touched',
        'prefixes': [
            '- active table authority lock:',
            '- table authority source type:',
            '- table authority source file path:',
            '- table authority manuscript binding proof:',
            '- table authority rationale:',
            '- active table authority source summary:',
            '- table authority checkpoints:',
            '- table-local structure evidence record paths:',
            '- table-local structure checkpoints:',
            '- rendered table baseline comparison evidence record paths:',
        ],
    },
    'style_blast_radius': {
        'message': 'format-repair task record must lock cross-surface regression data when body/default styles are touched',
        'prefixes': [
            '- style-blast-radius trigger:',
            '- protected-surface freeze manifest path:',
            '- protected_surface_freeze_manifest verdict:',
            '- pre-mutation protected-surface snapshot path:',
            '- post-mutation protected-surface snapshot path:',
            '- post_mutation_surface_diff path:',
            '- post_mutation_surface_diff verdict:',
            '- target_surface_render_review path:',
            '- target_surface_render_review verdict:',
            '- blast_radius_render_review path:',
            '- blast_radius_render_review verdict:',
            '- cross_surface_regression_report path:',
            '- cross_surface_regression_report verdict:',
            '- non-target protected surface change verdict:',
            '- chapter_format_preservation_report path:',
            '- chapter_format_preservation_report sha256:',
            '- chapter_format_preservation_report verdict:',
            '- chapter format preservation detector verdict:',
            '- non-target format preservation verdict:',
            '- cross-surface regression diff path:',
            '- cross-surface regression owner:',
            '- TOC underline pollution detector required?:',
            '- table style regression detector required?:',
            '- cross-surface regression freeze evidence path:',
            '- TOC underline pollution evidence path:',
            '- table style regression evidence path:',
            '- cross-surface regression verdict:',
            '- TOC underline pollution verdict:',
            '- table style regression verdict:',
        ],
    },
    'tail_block': {
        'message': 'format-repair task record must lock tail-block pagination data when tail blocks are touched',
        'prefixes': [
            '- tail-block pagination repair included this round?:',
            '- tail-block titles in scope:',
            '- tail-block title baseline source file path:',
            '- references title baseline paragraph/run path:',
            '- references entries baseline paragraph/run path:',
            '- acknowledgement title baseline paragraph/run path:',
            '- acknowledgement body baseline paragraph/run path:',
            '- end-matter indentation detector required?:',
            '- tail-block opener ownership baseline:',
            '- tail-block pagination restoration owner:',
            '- tail-block opener page-occupancy baseline:',
            '- tail-block title baseline paragraph paths:',
            '- references title indentation baseline:',
            '- references entries left/hanging indentation baseline:',
            '- acknowledgement title indentation baseline:',
            '- acknowledgement body indentation baseline:',
            '- tail-block pagination checkpoints:',
            '- references title indentation checkpoints:',
            '- references entries indentation checkpoints:',
            '- acknowledgement title indentation checkpoints:',
            '- acknowledgement body indentation checkpoints:',
            '- end-matter rendered geometry checkpoints:',
            '- tail-block pagination evidence record paths:',
            '- tail-block rendered opener comparison evidence record paths:',
            '- references title indentation evidence record path:',
            '- references entries indentation evidence record path:',
            '- acknowledgement title indentation evidence record path:',
            '- acknowledgement body indentation evidence record path:',
        ],
    },
    'toc': {
        'message': 'format-repair task record must lock TOC baseline data when TOC is touched',
        'prefixes': [
            '- TOC baseline-source lock:',
            '- TOC baseline source file path:',
            '- TOC implementation type in baseline source:',
            '- TOC restoration source allowed to be current working draft?:',
            '- TOC title visual metrics baseline:',
            '- TOC level-1 visual metrics baseline:',
            '- TOC level-2 visual metrics baseline:',
            '- TOC level-3 visual metrics baseline:',
            '- TOC title paragraph-dialog / typography metrics baseline:',
            '- TOC level-1 paragraph-dialog / typography metrics baseline:',
            '- TOC level-2 paragraph-dialog / typography metrics baseline:',
            '- TOC level-3 paragraph-dialog / typography metrics baseline:',
            '- TOC visible-run direct typography baseline:',
            '- TOC per-level text/tab/page-number run typography baseline:',
            '- TOC per-level style-binding baseline:',
            '- TOC scale/compression baseline verdict:',
            '- TOC page-count / occupancy baseline:',
            '- TOC visual geometry baseline:',
            '- TOC post-refresh restoration owner:',
            '- TOC title baseline paragraph path:',
            '- TOC level-1 baseline paragraph path:',
            '- TOC level-2 baseline paragraph path:',
            '- TOC level-3 baseline paragraph path:',
            '- TOC right-tab position baseline:',
            '- TOC line-spacing baseline:',
            '- TOC paragraph before/after spacing baseline:',
            '- TOC line-spacing mode/value baseline:',
            '- TOC indentation chars/points baseline:',
            '- TOC per-level font-size/weight baseline:',
            '- TOC dotted-leader baseline:',
            '- TOC page-number column per-entry baseline:',
            '- TOC title bbox baseline:',
            '- TOC entry row bbox baseline:',
            '- TOC per-level left-indent x baseline:',
            '- TOC line-spacing y-delta baseline:',
            '- TOC dotted-leader start/end/density baseline:',
            '- TOC page-number x column baseline:',
            '- TOC row-count / page-occupancy rhythm baseline:',
            '- TOC restoration checkpoints:',
            '- TOC post-refresh restoration evidence record paths:',
            '- TOC rendered baseline comparison evidence record paths:',
            '- TOC visual geometry evidence record paths:',
            '- TOC paragraph-and-typography evidence record paths:',
            '- TOC visible-run typography evidence record paths:',
            '- TOC visible-run typography verdict:',
            '- front-matter numbering convention expected on rendered pages:',
            '- office-app path used to verify adjusted page numbers:',
        ],
    },
}

FORMAT_REPAIR_TASK_TOUCH_CONTEXT_RAW_PREFIXES = [
    '- touched blocks this round:',
    '- specific format classes to verify:',
    '- explicit user rule:',
    '- TOC repair included this round?:',
    '- live TOC required this round?:',
    '- touched header/footer surfaces:',
    '- active table authority source summary:',
    '- tail-block pagination repair included this round?:',
    '- tail-block titles in scope:',
    '- style-blast-radius trigger:',
]

FORMULA_HINT_TOKENS = (
    'formula',
    'equation',
    '\u516c\u5f0f',
    '\u5f0f4-',
    '\u5f0f',
)

GATE_SINGLE_PREFIX_POLICY = {
    '- TOC / bookmark integrity summary:': 'explicit_nonempty',
    '- Normal baseline preservation summary:': 'explicit_nonempty',
    '- acceptance record path:': 'explicit_nonempty',
    '- active checklist names:': 'explicit_nonempty',
    '- agent authorization source:': 'explicit_or_none',
    '- agent mode:': 'explicit_nonempty',
    '- required lanes:': 'explicit_nonempty',
    '- agent role aliases zh:': 'explicit_nonempty',
    '- required lane aliases zh:': 'explicit_nonempty',
    '- spawned agent aliases zh:': 'explicit_or_none',
    '- lane alias map zh:': 'explicit_nonempty',
    '- audit role alias zh:': 'exact_value:\u5ba1\u6838',
    '- spawned agent ids:': 'explicit_or_none',
    '- audit agent id:': 'explicit_or_none',
    '- sequential audit fallback id:': 'explicit_or_none',
    '- audit spawn or fallback mode:': 'explicit_nonempty',
    '- audit verdict:': 'exact_value:pass',
    '- audit verdict cadence:': 'explicit_nonempty',
    '- handoff status:': 'exact_value:pass',
    '- known caveats:': 'explicit_none',
    '- baseline promotion status:': 'explicit_nonempty',
    '- baseline promotion evidence path:': 'thesis_evidence',
    '- release blocker ledger path:': 'thesis_evidence',
    '- unresolved release blocker count:': 'explicit_nonempty',
    '- scoped artifact next-baseline verdict:': 'explicit_nonempty',
    '- action audit scope:': 'explicit_nonempty',
    '- action audit verdict cadence:': 'explicit_nonempty',
    '- action audit verdicts:': 'explicit_nonempty',
    '- action cycles:': 'explicit_nonempty',
    '- action categories:': 'explicit_nonempty',
    '- action owner map:': 'explicit_nonempty',
    '- skill invocation lock path:': 'explicit_nonempty',
    '- skill invocation lock verdict:': 'explicit_nonempty',
    '- skill invocation verified:': 'explicit_nonempty',
    '- routed references verified:': 'explicit_nonempty',
    '- active checklist verified:': 'explicit_nonempty',
    '- user request compliance verdict:': 'explicit_nonempty',
    '- loaded rule compliance verdict:': 'explicit_nonempty',
    '- sequential fallback reason:': 'explicit_or_none',
    '- agent run manifest path:': 'explicit_nonempty',
    '- lightweight action-audit entry path:': 'explicit_or_none',
    '- lane task card evidence paths:': 'explicit_nonempty',
    '- agent id alias map:': 'explicit_nonempty',
    '- controlled bookmark disposition path:': 'explicit_or_none',
    '- bibliography audit evidence path:': 'paper_only_evidence',
    '- bibliography empty-entry/content completeness evidence path:': 'thesis_evidence',
    '- bibliography empty-entry/content completeness verdict:': 'explicit_nonempty',
    '- citation audit evidence path:': 'thesis_evidence',
    '- citation anchor pollution audit path:': 'thesis_evidence',
    '- custom-layout result-table preservation summary:': 'explicit_nonempty',
    '- body paragraph family consistency summary:': 'explicit_nonempty',
    '- body style audit evidence path:': 'thesis_evidence',
    '- body style binding summary:': 'explicit_nonempty',
    '- surface-face parity summary:': 'explicit_nonempty',
    '- sibling-surface audit summary:': 'explicit_nonempty',
    '- cross-surface regression freeze evidence path:': 'thesis_evidence',
    '- style-blast-radius escalation summary:': 'explicit_nonempty',
    '- cross-surface regression verdict:': 'explicit_nonempty',
    '- TOC underline pollution verdict:': 'explicit_nonempty',
    '- table style regression verdict:': 'explicit_nonempty',
    '- table donor title mode:': 'explicit_nonempty',
    '- table target title mode:': 'explicit_nonempty',
    '- table title-mode verdict:': 'explicit_nonempty',
    '- table in-table merged-title-row verdict:': 'explicit_nonempty',
    '- table top rule verdict:': 'explicit_nonempty',
    '- table header separator rule verdict:': 'explicit_nonempty',
    '- table body middle-rule policy verdict:': 'explicit_nonempty',
    '- table bottom rule verdict:': 'explicit_nonempty',
    '- table rendered crop metric json path:': 'thesis_evidence',
    '- font-family baseline summary:': 'explicit_nonempty',
    '- builder/default font rejection summary:': 'explicit_nonempty',
    '- code title formatting summary:': 'explicit_nonempty',
    '- code block formatting summary:': 'explicit_nonempty',
    '- abstract baseline preservation summary:': 'explicit_nonempty',
    '- abstract and keyword surface verdict:': 'explicit_nonempty',
    '- keyword content title-style contamination evidence path:': 'thesis_evidence',
    '- keyword content title-style contamination verdict:': 'explicit_nonempty',
    '- cover style evidence path:': 'thesis_evidence',
    '- cover style verdict:': 'explicit_nonempty',
    '- cover identity value-line evidence path:': 'thesis_evidence',
    '- cover identity value-line verdict:': 'explicit_nonempty',
    '- cover value cell targeted verdict:': 'explicit_nonempty',
    '- cover label cell unchanged verdict:': 'explicit_nonempty',
    '- cover underline x/y/width evidence path:': 'thesis_evidence',
    '- cover value text bbox evidence path:': 'thesis_evidence',
    '- cover value-on-underline verdict:': 'explicit_nonempty',
    '- cover row baseline alignment verdict:': 'explicit_nonempty',
    '- declaration/title front matter evidence path:': 'thesis_evidence',
    '- declaration/title front matter verdict:': 'explicit_nonempty',
    '- Chinese abstract title evidence path:': 'thesis_evidence',
    '- Chinese abstract title verdict:': 'explicit_nonempty',
    '- Chinese abstract body evidence path:': 'thesis_evidence',
    '- Chinese abstract body verdict:': 'explicit_nonempty',
    '- Chinese keyword line evidence path:': 'thesis_evidence',
    '- Chinese keyword line verdict:': 'explicit_nonempty',
    '- English abstract title evidence path:': 'thesis_evidence',
    '- English abstract title verdict:': 'explicit_nonempty',
    '- English abstract body evidence path:': 'thesis_evidence',
    '- English abstract body verdict:': 'explicit_nonempty',
    '- English keyword line evidence path:': 'thesis_evidence',
    '- English keyword line verdict:': 'explicit_nonempty',
    '- heading baseline preservation summary:': 'explicit_nonempty',
    '- docx font/encoding audit evidence path:': 'thesis_evidence',
    '- per-surface mixed-script font-slot matrix path:': 'thesis_evidence',
    '- per-surface mixed-script font-slot verdict:': 'explicit_nonempty',
    '- exact output paths:': 'explicit_nonempty',
    '- failed with reasons:': 'explicit_none',
    '- filled format-repair task record path:': 'format_repair_nonempty',
    '- heading family preservation summary:': 'explicit_nonempty',
    '- heading level 1 verdict:': 'explicit_nonempty',
    '- heading level 2 verdict:': 'explicit_nonempty',
    '- heading level 3 verdict:': 'explicit_nonempty',
    '- heading level 4 verdict:': 'explicit_nonempty',
    '- heading direct rPr/font/size/bold/spacing verdict:': 'explicit_nonempty',
    '- helper-script target path lock:': 'explicit_nonempty',
    '- humanizer evidence path:': 'humanizer_evidence',
    '- humanizer route decision:': 'explicit_or_none',
    '- humanizer scope:': 'explicit_or_none',
    '- humanizer target language:': 'explicit_or_none',
    '- humanizer manual or skill run id:': 'explicit_or_none',
    '- humanizer processed paragraph count:': 'explicit_or_none',
    '- humanizer changed pattern list:': 'explicit_or_none',
    '- humanizer no meta-evaluation voice verdict:': 'explicit_or_none',
    '- verification scope claim:': 'explicit_nonempty',
    '- sample self-check report path:': 'explicit_or_none',
    '- page-class coverage matrix evidence path:': 'explicit_or_none',
    '- mandatory thesis surface inventory path:': 'explicit_or_none',
    '- front matter surface coverage matrix path:': 'explicit_or_none',
    '- end matter surface coverage matrix path:': 'explicit_or_none',
    '- high-risk thesis format surface matrix path:': 'explicit_or_none',
    '- user-reported issue ledger path:': 'explicit_or_none',
    '- comment-resolution ledger path:': 'explicit_or_none',
    '- comment-resolution audit report path:': 'explicit_or_none',
    '- comment-resolution audit verdict:': 'explicit_or_none',
    '- figure asset manifest path:': 'explicit_or_none',
    '- figure user material source path:': 'explicit_or_none',
    '- figure user material source SHA256:': 'explicit_or_none',
    '- figure material-source inventory path:': 'explicit_or_none',
    '- figure material-source binding verdict:': 'explicit_or_none',
    '- figure generated-substitute rejection verdict:': 'explicit_or_none',
    '- figure extents audit path:': 'explicit_or_none',
    '- figure paragraph-margin width verdict:': 'explicit_or_none',
    '- figure visible-content completeness verdict:': 'explicit_or_none',
    '- figure nonzero crop count:': 'explicit_or_none',
    '- figure exact-line-spacing clipping count:': 'explicit_or_none',
    '- figure image-holder layout verdict:': 'explicit_or_none',
    '- figure image-holder layout issue count:': 'explicit_or_none',
    '- runtime screenshot full-window geometry evidence paths:': 'explicit_or_none',
    '- runtime screenshot full-window capture verdict:': 'explicit_or_none',
    '- algorithm result authenticity evidence paths:': 'explicit_or_none',
    '- algorithm result source/provenance evidence paths:': 'explicit_or_none',
    '- algorithm result caption-to-asset map path:': 'explicit_or_none',
    '- algorithm result system search / startup attempt path:': 'explicit_or_none',
    '- algorithm result provenance verdict:': 'explicit_or_none',
    '- code screenshot authenticity evidence paths:': 'explicit_or_none',
    '- algorithm code visibility evidence path:': 'explicit_or_none',
    '- algorithm code visibility verdict:': 'explicit_or_none',
    '- TOC digits/cache preservation evidence path:': 'explicit_or_none',
    '- TOC digits/cache preservation verdict:': 'explicit_or_none',
    '- flowchart semantic trigger inventory path:': 'explicit_or_none',
    '- flowchart draw.io source evidence paths:': 'explicit_or_none',
    '- flowchart SVG export evidence paths:': 'explicit_or_none',
    '- flowchart raster fallback evidence paths:': 'explicit_or_none',
    '- flowchart source-scale geometry report paths:': 'explicit_or_none',
    '- flowchart rendered-page evidence paths:': 'explicit_or_none',
    '- flowchart final DOCX relationship evidence paths:': 'explicit_or_none',
    '- flowchart manifest contract verdict:': 'explicit_or_none',
    '- figure source/style contract summary:': 'explicit_or_none',
    '- touched template-owned surface families:': 'explicit_or_none',
    '- template discovery report path:': 'thesis_evidence',
    '- template profile generation command:': 'command:thesis_template_profile',
    '- template profile generated before mutation?:': 'exact_value:yes',
    '- locked path encoding verdict:': 'exact_value:pass',
    '- contaminated intermediate source used?:': 'exact_value:no',
    '- contaminated intermediate source disposition:': 'explicit_or_none',
    '- protected-surface evidence contract path:': 'explicit_nonempty',
    '- protected-surface evidence contract loaded?:': 'explicit_nonempty',
    '- canonical protected surface id set:': 'explicit_nonempty',
    '- protected-surface owner map:': 'explicit_nonempty',
    '- protected-surface evidence map:': 'explicit_or_none',
    '- protected-surface reviewed output sha256:': 'explicit_or_none',
    '- protected-surface evidence contract verdict:': 'explicit_nonempty',
    '- protected surface contract evidence path:': 'explicit_nonempty',
    '- surface-face parity baseline locks:': 'explicit_or_none',
    '- surface paragraph-and-typography audit evidence path:': 'thesis_evidence',
    '- surface paragraph-and-typography summary:': 'explicit_nonempty',
    '- surface paragraph-and-typography verdict:': 'explicit_nonempty',
    '- custom/builder/default font usage allowed?:': 'exact_value:no',
    '- font baseline blockers:': 'explicit_or_none',
    '- loaded references:': 'explicit_nonempty',
    '- machine-vision summary by touched surface:': 'format_repair_nonempty',
    '- page-image artifact paths:': 'format_repair_nonempty',
    '- post-script smoke-audit summary:': 'explicit_nonempty',
    '- protected-surface ownership lock:': 'explicit_nonempty',
    '- rendered PDF path:': 'format_repair_nonempty',
    '- review-copy path actually rendered:': 'format_repair_nonempty',
    '- footer baseline typography summary:': 'explicit_nonempty',
    '- TOC visual baseline verdict:': 'explicit_nonempty',
    '- TOC visual geometry verdict:': 'explicit_nonempty',
    '- TOC paragraph-and-typography verdict:': 'explicit_nonempty',
    '- TOC visible-run typography verdict:': 'explicit_nonempty',
    '- TOC title evidence path:': 'thesis_evidence',
    '- TOC title verdict:': 'explicit_nonempty',
    '- TOC entries evidence path:': 'thesis_evidence',
    '- TOC entries verdict:': 'explicit_nonempty',
    '- TOC dotted leaders evidence path:': 'thesis_evidence',
    '- TOC dotted leaders verdict:': 'explicit_nonempty',
    '- TOC page-number column evidence path:': 'thesis_evidence',
    '- TOC page-number column verdict:': 'explicit_nonempty',
    '- TOC implementation family/live-field parity evidence path:': 'thesis_evidence',
    '- TOC implementation family/live-field parity verdict:': 'explicit_nonempty',
    '- TOC per-level template baseline evidence path:': 'thesis_evidence',
    '- TOC rendered geometry comparison path:': 'thesis_evidence',
    '- TOC title/level font and paragraph metrics verdict:': 'explicit_nonempty',
    '- TOC dotted leader and page-number column verdict:': 'explicit_nonempty',
    '- TOC occupancy rhythm verdict:': 'explicit_nonempty',
    '- body heading levels evidence path:': 'thesis_evidence',
    '- body heading levels verdict:': 'explicit_nonempty',
    '- body text evidence path:': 'thesis_evidence',
    '- body text verdict:': 'explicit_nonempty',
    '- chapter format preservation detector verdict:': 'explicit_nonempty',
    '- chapter format diff path:': 'explicit_nonempty',
    '- touched chapter rendered evidence paths:': 'thesis_evidence',
    '- references title evidence path:': 'thesis_evidence',
    '- references title verdict:': 'explicit_nonempty',
    '- references entries evidence path:': 'thesis_evidence',
    '- rendered references-page evidence path:': 'thesis_evidence',
    '- references entries verdict:': 'explicit_nonempty',
    '- acknowledgement title evidence path:': 'thesis_evidence',
    '- acknowledgement title verdict:': 'explicit_nonempty',
    '- acknowledgement body evidence path:': 'thesis_evidence',
    '- acknowledgement body verdict:': 'explicit_nonempty',
    '- header evidence path:': 'thesis_evidence',
    '- header verdict:': 'explicit_nonempty',
    '- header presence verdict:': 'explicit_nonempty',
    '- header rendered verdict:': 'explicit_nonempty',
    '- header expected display string source:': 'explicit_nonempty',
    '- header rendered full-display evidence path:': 'thesis_evidence',
    '- header chapter number preservation verdict:': 'explicit_nonempty',
    '- body opener/header title consistency evidence path:': 'thesis_evidence',
    '- body opener/header title consistency verdict:': 'explicit_nonempty',
    '- format preservation promise active?:': 'explicit_nonempty',
    '- format preservation promise source:': 'explicit_or_none',
    '- format preservation promise verdict:': 'explicit_nonempty',
    '- non-target format preservation verdict:': 'explicit_nonempty',
    '- footer evidence path:': 'thesis_evidence',
    '- footer verdict:': 'explicit_nonempty',
    '- page numbers evidence path:': 'thesis_evidence',
    '- page numbers verdict:': 'explicit_nonempty',
    '- user-reported visual defect surfaces:': 'explicit_or_none',
    '- user-reported visual defect render-geometry evidence path:': 'explicit_or_none',
    '- user-reported visual defect template-vs-target binding verdict:': 'explicit_or_none',
    '- user-reported visual defect full-page/key-surface binding verdict:': 'explicit_or_none',
    '- toc visual geometry evidence paths:': 'thesis_evidence',
    '- toc paragraph-and-typography evidence paths:': 'thesis_evidence',
    '- toc visible-run typography evidence paths:': 'thesis_evidence',
    '- whole-document pagination evidence path:': 'thesis_evidence',
    '- frontmatter/TOC repair report path:': 'explicit_or_none',
    '- final DOCX list-pollution audit path:': 'thesis_evidence',
    '- final DOCX list-pollution audit verdict:': 'explicit_nonempty',
    '- whole-format list_pollution_audit verdict:': 'explicit_nonempty',
    '- whole-document pagination verdict:': 'explicit_nonempty',
    '- exact final CAD delivery package path:': 'explicit_or_none',
    '- exact final CAD delivery package sha256:': 'explicit_or_none',
    '- exact DWG package path:': 'explicit_or_none',
    '- exact DWG package sha256:': 'explicit_or_none',
    '- exact combined drawing PDF path:': 'explicit_or_none',
    '- exact combined drawing PDF sha256:': 'explicit_or_none',
    '- mechanical drawing package audit path:': 'explicit_or_none',
    '- mechanical drawing package audit verdict:': 'explicit_or_none',
    '- mechanical drawing formal CAD source provenance verdict:': 'explicit_or_none',
    '- mechanical drawing schematic/concept substitute rejection verdict:': 'explicit_or_none',
    '- mechanical drawing package exact package path:': 'explicit_or_none',
    '- mechanical drawing package exact package sha256:': 'explicit_or_none',
    '- mechanical drawing rendered review evidence paths:': 'explicit_or_none',
    '- mechanical drawing rendered no-overlap verdict:': 'explicit_or_none',
    '- mechanical drawing boundary clearance verdict:': 'explicit_or_none',
    '- mechanical drawing detail density verdict:': 'explicit_or_none',
    '- mechanical drawing title block/table/notes isolation verdict:': 'explicit_or_none',
    '- mechanical drawing title-block cell containment verdict:': 'explicit_or_none',
    '- mechanical drawing annotation margin clearance verdict:': 'explicit_or_none',
    '- mechanical drawing local crowding verdict:': 'explicit_or_none',
    '- mechanical drawing text/table/frame overlap verdict:': 'explicit_or_none',
    '- mechanical render readability audit path:': 'explicit_or_none',
    '- mechanical render readability verdict:': 'explicit_or_none',
    '- mechanical render readability source lineweight verdict:': 'explicit_or_none',
    '- mechanical render readability render-only stroke cap:': 'explicit_or_none',
    '- mechanical render readability render-only lineweight scaling:': 'explicit_or_none',
    '- text text overlap count:': 'explicit_or_none',
    '- text graphic cover count:': 'explicit_or_none',
    '- severe line crowding count:': 'explicit_or_none',
    '- mechanical render readability small-tile threshold:': 'explicit_or_none',
    '- mechanical render readability failed sheet list:': 'explicit_or_none',
    '- mechanical render readability requires crop review count:': 'explicit_or_none',
    '- mechanical render readability line bundle blocker count:': 'explicit_or_none',
    '- mechanical render readability diagnostic-overlay-free crop review path:': 'explicit_or_none',
    '- mechanical render readability standard-sheet view occupancy verdict:': 'explicit_or_none',
    '- mechanical render readability final PDF/PNG SHA evidence:': 'explicit_or_none',
    '- mechanical drawing machine overlap audit verdict:': 'explicit_or_none',
    '- mechanical drawing content-overlap audit verdict:': 'explicit_or_none',
    '- mechanical drawing content-overlap evidence path:': 'explicit_or_none',
    '- mechanical drawing registered content bbox count:': 'explicit_or_none',
    '- mechanical drawing checked content pair count:': 'explicit_or_none',
    '- mechanical drawing content overlap count:': 'explicit_or_none',
    '- mechanical drawing view-view overlap count:': 'explicit_or_none',
    '- mechanical drawing detail-frame-main-view overlap count:': 'explicit_or_none',
    '- mechanical drawing table text/grid collision count:': 'explicit_or_none',
    '- mechanical drawing dimension-line view/table crossing count:': 'explicit_or_none',
    '- mechanical drawing leader-line view/table crossing count:': 'explicit_or_none',
    '- mechanical drawing balloon geometry collision count:': 'explicit_or_none',
    '- mechanical drawing bbox helper envelope escape count:': 'explicit_or_none',
    '- mechanical drawing stale rendered preview count:': 'explicit_or_none',
    '- mechanical drawing outside-frame ink audit verdict:': 'explicit_or_none',
    '- mechanical drawing outside-frame ink audit evidence path:': 'explicit_or_none',
    '- mechanical drawing outside-frame independent ink component count:': 'explicit_or_none',
    '- mechanical drawing outside-frame text component count:': 'explicit_or_none',
    '- mechanical drawing outside-frame leader component count:': 'explicit_or_none',
    '- mechanical drawing outside-frame hatch/section component count:': 'explicit_or_none',
    '- mechanical drawing outside-frame table/title-block component count:': 'explicit_or_none',
    '- mechanical drawing inner-frame safe-margin audit verdict:': 'explicit_or_none',
    '- mechanical drawing inner-frame safe-margin evidence path:': 'explicit_or_none',
    '- mechanical drawing right safe-boundary intrusion count:': 'explicit_or_none',
    '- mechanical drawing leader-text inner-frame intrusion count:': 'explicit_or_none',
    '- mechanical drawing view-geometry inner-frame intrusion count:': 'explicit_or_none',
    '- mechanical drawing dimension-text inner-frame intrusion count:': 'explicit_or_none',
    '- mechanical drawing annotation ownership audit verdict:': 'explicit_or_none',
    '- mechanical drawing unowned free text count:': 'explicit_or_none',
    '- mechanical drawing unsupported floating text count:': 'explicit_or_none',
    '- mechanical drawing reserved-zone intrusion audit verdict:': 'explicit_or_none',
    '- mechanical drawing reserved-zone intrusion count:': 'explicit_or_none',
    '- mechanical drawing dimension-line table-zone intrusion count:': 'explicit_or_none',
    '- mechanical drawing dimension-text table-zone intrusion count:': 'explicit_or_none',
    '- mechanical drawing view-geometry reserved-zone intrusion count:': 'explicit_or_none',
    '- mechanical drawing hatch/section fill clipping audit verdict:': 'explicit_or_none',
    '- mechanical drawing hatch/section fill clipping evidence path:': 'explicit_or_none',
    '- mechanical drawing hatch/section fill boundary violation count:': 'explicit_or_none',
    '- mechanical drawing hatch/section fill adjacent-view crossing count:': 'explicit_or_none',
    '- mechanical drawing hatch/section fill dimension-line crossing count:': 'explicit_or_none',
    '- mechanical drawing hatch/section fill title-block/table/BOM/frame crossing count:': 'explicit_or_none',
    '- mechanical drawing hatch/section fill blank-background leak count:': 'explicit_or_none',
    '- mechanical drawing text entity overlap count:': 'explicit_or_none',
    '- mechanical drawing text legibility machine audit verdict:': 'explicit_or_none',
    '- mechanical drawing minimum CAD text height mm:': 'explicit_or_none',
    '- mechanical drawing minimum rendered text height px:': 'explicit_or_none',
    '- mechanical drawing text integrity audit path:': 'explicit_or_none',
    '- mechanical drawing text integrity audit verdict:': 'explicit_or_none',
    '- mechanical drawing mojibake/tofu/missing glyph count:': 'explicit_or_none',
    '- mechanical drawing missing required drawing text count:': 'explicit_or_none',
    '- mechanical drawing text orientation audit path:': 'explicit_or_none',
    '- mechanical drawing text orientation audit verdict:': 'explicit_or_none',
    '- mechanical drawing upside-down text count:': 'explicit_or_none',
    '- mechanical drawing mirrored text count:': 'explicit_or_none',
    '- mechanical drawing lineweight/linetype fidelity audit path:': 'explicit_or_none',
    '- mechanical drawing lineweight/linetype fidelity audit verdict:': 'explicit_or_none',
    '- mechanical drawing lineweight/linetype fidelity package sha256:': 'explicit_or_none',
    '- mechanical drawing color-family audit path:': 'explicit_or_none',
    '- mechanical drawing color-family audit verdict:': 'explicit_or_none',
    '- mechanical drawing color-family package/path sha256:': 'explicit_or_none',
    '- mechanical drawing thin-solid-white-only verdict:': 'explicit_or_none',
    '- mechanical drawing non-thin white layer/entity count:': 'explicit_or_none',
    '- mechanical drawing expected color family count:': 'explicit_or_none',
    '- mechanical drawing entity color override count:': 'explicit_or_none',
    '- mechanical drawing source line family coverage verdict:': 'explicit_or_none',
    '- mechanical drawing PDF page-box sheet-size audit verdict:': 'explicit_or_none',
    '- mechanical drawing rendered ink contrast audit verdict:': 'explicit_or_none',
    '- mechanical drawing worst readable ink ratio:': 'explicit_or_none',
    '- mechanical drawing minimum readable ink ratio:': 'explicit_or_none',
    '- mechanical drawing effective DWG byte-density ratio:': 'explicit_or_none',
    '- mechanical drawing estimated PDF sheet workload:': 'explicit_or_none',
    '- mechanical drawing A-series page box count:': 'explicit_or_none',
    '- mechanical drawing thick solid family count:': 'explicit_or_none',
    '- mechanical drawing thin solid family count:': 'explicit_or_none',
    '- mechanical drawing center dash-dot family count:': 'explicit_or_none',
    '- mechanical drawing hidden dashed family count:': 'explicit_or_none',
    '- mechanical drawing section hatch family count:': 'explicit_or_none',
    '- mechanical drawing manufacturing complexity audit verdict:': 'explicit_or_none',
    '- mechanical drawing minimum manufacturing detail family count:': 'explicit_or_none',
    '- mechanical drawing entity-count-only false-pass verdict:': 'explicit_or_none',
    '- CAD appendix binding audit path:': 'explicit_or_none',
    '- CAD appendix binding audit verdict:': 'explicit_or_none',
    '- CAD appendix matched sheet count:': 'explicit_or_none',
    '- CAD appendix missing sheet count:': 'explicit_or_none',
    '- CAD appendix final DOCX SHA256:': 'explicit_or_none',
    '- CAD appendix final package path:': 'explicit_or_none',
    '- formula narrative-context verdict:': 'explicit_or_none',
    '- formula dump marker count:': 'explicit_or_none',
    '- formula without nearby body explanation count:': 'explicit_or_none',
    '- formula narrative style issue count:': 'explicit_or_none',
    '- orphan formula style issue count:': 'explicit_or_none',
    '- formula duplicate-density verdict:': 'explicit_or_none',
    '- unique formula ratio:': 'explicit_or_none',
    '- duplicate formula body text count:': 'explicit_or_none',
    '- forbidden substitute evidence used?:': 'exact_value:no',
    '- references entry format verdict:': 'explicit_nonempty',
    '- appendix format verdict:': 'explicit_nonempty',
    '- high-risk thesis format surface verdict:': 'explicit_nonempty',
    '- skill selftest command:': 'command:selftest_skill_flow',
    '- skill selftest result:': 'exact_value:pass',
    '- subtask:': 'explicit_nonempty',
    '- task mode:': 'explicit_nonempty',
    '- validation command:': 'command:validate_skill_gate',
    '- validation result:': 'exact_value:pass',
    '- verified rasterizer path:': 'format_repair_nonempty',
    '- verified renderer path:': 'format_repair_nonempty',
}

HEADER_FOOTER_HINT_TOKENS = (
    'header',
    'footer',
    'page number',
    'header/footer',
    '\u9875\u7709',
    '\u9875\u811a',
    '\u9875\u7801',
)

NON_CONTENT_THESIS_HINT_TOKENS = (
    'format',
    'footer',
    'header',
    'toc',
    'caption',
    'figure',
    'screenshot',
    'citation',
    'bibliography',
    'table',
    'pagination',
    'repair',
    '\u683c\u5f0f',
    '\u9875\u7709',
    '\u9875\u811a',
    '\u76ee\u5f55',
    '\u56fe',
    '\u8868',
    '\u5f15\u6587',
)

NUMBERING_PARAGRAPH_TOKENS = (
    'numbering paragraph',
    'numbering paragraphs',
    '\u7f16\u53f7\u6bb5',
    '\u72ec\u7acb\u7f16\u53f7\u6bb5',
)

PATH_FIELD_PREFIXES = [
    '- filled format-repair task record path:',
    '- review-copy path actually rendered:',
    '- rendered PDF path:',
    '- full rendered page/footer map path:',
    '- page-image artifact paths:',
    '- final DOCX whole-format structural audit path:',
    '- final DOCX list-pollution audit path:',
    '- final DOCX font-color audit path:',
    '- exact output paths:',
    '- baseline promotion evidence path:',
    '- release blocker ledger path:',
    '- agent run manifest path:',
    '- lane task card evidence paths:',
    '- sample self-check report path:',
    '- chapter format diff path:',
    '- touched chapter rendered evidence paths:',
    '- page-class coverage matrix evidence path:',
    '- mandatory thesis surface inventory path:',
    '- front matter surface coverage matrix path:',
    '- end matter surface coverage matrix path:',
    '- high-risk thesis format surface matrix path:',
    '- cover style evidence path:',
    '- declaration/title front matter evidence path:',
    '- cover underline x/y/width evidence path:',
    '- cover value text bbox evidence path:',
    '- Chinese abstract title evidence path:',
    '- Chinese abstract body evidence path:',
    '- Chinese keyword line evidence path:',
    '- English abstract title evidence path:',
    '- English abstract body evidence path:',
    '- English keyword line evidence path:',
    '- TOC title evidence path:',
    '- TOC entries evidence path:',
    '- TOC dotted leaders evidence path:',
    '- TOC page-number column evidence path:',
    '- body heading levels evidence path:',
    '- body text evidence path:',
    '- body citation superscripts evidence path:',
    '- review comments/change marks evidence path:',
    '- references title evidence path:',
    '- references entries evidence path:',
    '- rendered references-page evidence path:',
    '- acknowledgement title evidence path:',
    '- acknowledgement body evidence path:',
    '- header evidence path:',
    '- body opener/header title consistency evidence path:',
    '- footer evidence path:',
    '- page numbers evidence path:',
    '- user-reported issue ledger path:',
    '- content mutation rendered-page review path:',
    '- touched-page/blast-radius machine-vision evidence paths:',
    '- comment-resolution ledger path:',
    '- comment-resolution audit report path:',
    '- figure asset manifest path:',
    '- figure user material source path:',
    '- figure material-source inventory path:',
    '- figure extents audit path:',
    '- figure visible-content completeness verdict:',
    '- runtime screenshot full-window geometry evidence paths:',
    '- algorithm result authenticity evidence paths:',
    '- algorithm result source/provenance evidence paths:',
    '- algorithm result caption-to-asset map path:',
    '- algorithm result system search / startup attempt path:',
    '- code screenshot authenticity evidence paths:',
    '- algorithm code visibility evidence path:',
    '- TOC digits/cache preservation evidence path:',
    '- flowchart semantic trigger inventory path:',
    '- flowchart draw.io source evidence paths:',
    '- flowchart SVG export evidence paths:',
    '- flowchart raster fallback evidence paths:',
    '- flowchart source-scale geometry report paths:',
    '- flowchart rendered-page evidence paths:',
    '- flowchart final DOCX relationship evidence paths:',
    '- figure inventory path:',
    '- per-figure rendered evidence paths:',
    '- delegated canonical helper paths:',
    '- project-local helper preflight report path:',
    '- project template discovery root:',
    '- discovered candidate template paths:',
    '- active template path lock:',
    '- active template profile path:',
    '- template discovery report path:',
    '- toc restoration evidence paths:',
    '- toc rendered baseline comparison evidence paths:',
    '- toc visual geometry evidence paths:',
    '- toc paragraph-and-typography evidence paths:',
    '- toc visible-run typography evidence paths:',
    '- whole-document pagination evidence path:',
    '- frontmatter/TOC repair report path:',
    '- package baseline manifest path:',
    '- package drift report path:',
    '- pre-mutation page map path:',
    '- post-mutation page map path:',
    '- whole-document pagination diff path:',
    '- section break numbering map path:',
    '- chapter start owner map path:',
    '- tail-block owner map path:',
    '- TOC-to-heading page sync map path:',
    '- logical-physical page map path:',
    '- blank-page scan evidence path:',
    '- tail-block pagination evidence paths:',
    '- tail-block rendered opener comparison evidence paths:',
    '- table authority evidence paths:',
    '- table-local structure evidence paths:',
    '- table rendered baseline comparison evidence paths:',
    '- table title-mode evidence paths:',
    '- table header-bottom middle-rule evidence paths:',
    '- table rendered crop metric json path:',
    '- citation audit evidence path:',
    '- citation audit source-to-final run diff path:',
    '- citation anchor pollution audit path:',
    '- source review-artifact inventory path:',
    '- final review-artifact diff path:',
    '- controlled bookmark disposition path:',
    '- source body-citation run inventory path:',
    '- final body-citation run diff path:',
    '- bibliography label-family decision path:',
    '- bibliography audit evidence path:',
    '- bibliography empty-entry/content completeness evidence path:',
    '- reference rendered label geometry path:',
    '- formula object audit evidence path:',
    '- formula rendered label geometry path:',
    '- docx font/encoding audit evidence path:',
    '- per-surface mixed-script font-slot matrix path:',
    '- keyword content title-style contamination evidence path:',
    '- surface-face parity audit evidence path:',
    '- surface paragraph-and-typography audit evidence path:',
    '- sibling-surface audit evidence path:',
    '- font-family baseline audit evidence path:',
    '- active template profile evidence path:',
    '- body style audit evidence path:',
    '- program evidence paths:',
    '- thesis rendered-page evidence paths:',
    '- figure review evidence paths:',
    '- paragraph-review evidence paths:',
    '- touched-page review evidence paths:',
    '- humanizer evidence path:',
    '- exact final CAD delivery package path:',
    '- exact DWG package path:',
    '- exact combined drawing PDF path:',
    '- mechanical drawing package audit path:',
    '- mechanical drawing package exact package path:',
    '- mechanical drawing rendered review evidence paths:',
    '- CAD appendix binding audit path:',
    '- CAD appendix final package path:',
]

REQUIRED_NON_NONE_PATHS_BY_MODE = {
    'format-repair-only': {
        '- Chinese abstract body evidence path:',
        '- Chinese abstract title evidence path:',
        '- Chinese keyword line evidence path:',
        '- English abstract body evidence path:',
        '- English abstract title evidence path:',
        '- English keyword line evidence path:',
        '- TOC dotted leaders evidence path:',
        '- TOC entries evidence path:',
        '- TOC page-number column evidence path:',
        '- TOC title evidence path:',
        '- acknowledgement body evidence path:',
        '- acknowledgement title evidence path:',
        '- active template profile evidence path:',
        '- bibliography audit evidence path:',
        '- body citation superscripts evidence path:',
        '- body heading levels evidence path:',
        '- body opener/header title consistency evidence path:',
        '- body style audit evidence path:',
        '- chapter format diff path:',
        '- citation audit evidence path:',
        '- citation anchor pollution audit path:',
        '- citation audit source-to-final run diff path:',
        '- cover style evidence path:',
        '- declaration/title front matter evidence path:',
        '- docx font/encoding audit evidence path:',
        '- end matter surface coverage matrix path:',
        '- exact output paths:',
        '- final DOCX font-color audit path:',
        '- final DOCX list-pollution audit path:',
        '- final DOCX whole-format structural audit path:',
        '- filled format-repair task record path:',
        '- final body-citation run diff path:',
        '- final review-artifact diff path:',
        '- font-family baseline audit evidence path:',
        '- footer evidence path:',
        '- front matter surface coverage matrix path:',
        '- header evidence path:',
        '- high-risk thesis format surface matrix path:',
        '- mandatory thesis surface inventory path:',
        '- page numbers evidence path:',
        '- page-image artifact paths:',
        '- paragraph-review evidence paths:',
        '- project-local helper preflight report path:',
        '- references entries evidence path:',
        '- references title evidence path:',
        '- rendered PDF path:',
        '- rendered references-page evidence path:',
        '- review comments/change marks evidence path:',
        '- review-copy path actually rendered:',
        '- sample self-check report path:',
        '- sibling-surface audit evidence path:',
        '- source body-citation run inventory path:',
        '- source manuscript genealogy path:',
        '- source retention manifest path:',
        '- source review-artifact inventory path:',
        '- surface paragraph-and-typography audit evidence path:',
        '- surface-face parity audit evidence path:',
        '- template discovery report path:',
        '- thesis rendered-page evidence paths:',
        '- toc paragraph-and-typography evidence paths:',
        '- toc visible-run typography evidence paths:',
        '- toc visual geometry evidence paths:',
        '- touched chapter rendered evidence paths:',
        '- touched-page review evidence paths:',
        '- whole-document pagination evidence path:',
    },
    'program-only': {
        '- exact output paths:',
        '- program evidence paths:',
    },
    'program-plus-thesis': {
        '- Chinese abstract body evidence path:',
        '- Chinese abstract title evidence path:',
        '- Chinese keyword line evidence path:',
        '- English abstract body evidence path:',
        '- English abstract title evidence path:',
        '- English keyword line evidence path:',
        '- TOC dotted leaders evidence path:',
        '- TOC entries evidence path:',
        '- TOC page-number column evidence path:',
        '- TOC title evidence path:',
        '- acknowledgement body evidence path:',
        '- acknowledgement title evidence path:',
        '- active template profile evidence path:',
        '- bibliography audit evidence path:',
        '- body citation superscripts evidence path:',
        '- body heading levels evidence path:',
        '- body opener/header title consistency evidence path:',
        '- body style audit evidence path:',
        '- chapter format diff path:',
        '- citation audit evidence path:',
        '- citation anchor pollution audit path:',
        '- citation audit source-to-final run diff path:',
        '- cover style evidence path:',
        '- declaration/title front matter evidence path:',
        '- docx font/encoding audit evidence path:',
        '- end matter surface coverage matrix path:',
        '- exact output paths:',
        '- final DOCX font-color audit path:',
        '- final DOCX list-pollution audit path:',
        '- final DOCX whole-format structural audit path:',
        '- filled format-repair task record path:',
        '- final body-citation run diff path:',
        '- final review-artifact diff path:',
        '- font-family baseline audit evidence path:',
        '- footer evidence path:',
        '- front matter surface coverage matrix path:',
        '- header evidence path:',
        '- high-risk thesis format surface matrix path:',
        '- mandatory thesis surface inventory path:',
        '- page numbers evidence path:',
        '- page-image artifact paths:',
        '- paragraph-review evidence paths:',
        '- program evidence paths:',
        '- project-local helper preflight report path:',
        '- references entries evidence path:',
        '- references title evidence path:',
        '- rendered PDF path:',
        '- rendered references-page evidence path:',
        '- review comments/change marks evidence path:',
        '- review-copy path actually rendered:',
        '- sample self-check report path:',
        '- sibling-surface audit evidence path:',
        '- source body-citation run inventory path:',
        '- source manuscript genealogy path:',
        '- source retention manifest path:',
        '- source review-artifact inventory path:',
        '- surface paragraph-and-typography audit evidence path:',
        '- surface-face parity audit evidence path:',
        '- template discovery report path:',
        '- thesis rendered-page evidence paths:',
        '- toc paragraph-and-typography evidence paths:',
        '- toc visible-run typography evidence paths:',
        '- toc visual geometry evidence paths:',
        '- touched chapter rendered evidence paths:',
        '- touched-page review evidence paths:',
        '- whole-document pagination evidence path:',
    },
    'thesis-only': {
        '- Chinese abstract body evidence path:',
        '- Chinese abstract title evidence path:',
        '- Chinese keyword line evidence path:',
        '- English abstract body evidence path:',
        '- English abstract title evidence path:',
        '- English keyword line evidence path:',
        '- TOC dotted leaders evidence path:',
        '- TOC entries evidence path:',
        '- TOC page-number column evidence path:',
        '- TOC title evidence path:',
        '- acknowledgement body evidence path:',
        '- acknowledgement title evidence path:',
        '- active template profile evidence path:',
        '- bibliography audit evidence path:',
        '- body citation superscripts evidence path:',
        '- body heading levels evidence path:',
        '- body opener/header title consistency evidence path:',
        '- body style audit evidence path:',
        '- chapter format diff path:',
        '- citation audit evidence path:',
        '- citation anchor pollution audit path:',
        '- citation audit source-to-final run diff path:',
        '- cover style evidence path:',
        '- declaration/title front matter evidence path:',
        '- docx font/encoding audit evidence path:',
        '- end matter surface coverage matrix path:',
        '- exact output paths:',
        '- final DOCX font-color audit path:',
        '- final DOCX list-pollution audit path:',
        '- final DOCX whole-format structural audit path:',
        '- filled format-repair task record path:',
        '- final body-citation run diff path:',
        '- final review-artifact diff path:',
        '- font-family baseline audit evidence path:',
        '- footer evidence path:',
        '- front matter surface coverage matrix path:',
        '- header evidence path:',
        '- high-risk thesis format surface matrix path:',
        '- mandatory thesis surface inventory path:',
        '- page numbers evidence path:',
        '- page-image artifact paths:',
        '- paragraph-review evidence paths:',
        '- project-local helper preflight report path:',
        '- references entries evidence path:',
        '- references title evidence path:',
        '- rendered PDF path:',
        '- rendered references-page evidence path:',
        '- review comments/change marks evidence path:',
        '- review-copy path actually rendered:',
        '- sample self-check report path:',
        '- sibling-surface audit evidence path:',
        '- source body-citation run inventory path:',
        '- source manuscript genealogy path:',
        '- source retention manifest path:',
        '- source review-artifact inventory path:',
        '- surface paragraph-and-typography audit evidence path:',
        '- surface-face parity audit evidence path:',
        '- template discovery report path:',
        '- thesis rendered-page evidence paths:',
        '- toc paragraph-and-typography evidence paths:',
        '- toc visible-run typography evidence paths:',
        '- toc visual geometry evidence paths:',
        '- touched chapter rendered evidence paths:',
        '- touched-page review evidence paths:',
        '- whole-document pagination evidence path:',
    },
}

REVIEW_EVIDENCE_ALWAYS_REQUIRED_PREFIXES = [
    '- protected-surface evidence contract path:',
    '- reviewed output path:',
    '- reviewed output sha256:',
    '- evidence created after mutation?:',
    '- artifact path:',
    '- target surface:',
    '- target identifier:',
    '- canonical protected surface id:',
    '- protected surface owner lane:',
    '- protected surface audit lane:',
    '- checks performed:',
    '- summary:',
]

REVIEW_EVIDENCE_MAYBE_NOT_APPLICABLE_PREFIXES = [
    '- target pages or region:',
    '- blast-radius pages:',
    '- neighboring surfaces checked:',
]

REVIEW_EVIDENCE_OPTIONAL_STATUS_PREFIXES = [
    '- TOC title baseline confirmed:',
    '- TOC level formatting confirmed:',
    '- TOC dotted-leader / right-tab confirmed:',
    '- TOC page-number column confirmed:',
    '- TOC restored from locked baseline confirmed:',
    '- TOC page occupancy baseline confirmed:',
    '- TOC title paragraph confirmed:',
    '- TOC entries by level confirmed:',
    '- TOC dotted leaders confirmed:',
    '- TOC page-number column per entry confirmed:',
    '- heading level baseline confirmed:',
    '- heading direct-run typography confirmed:',
    '- heading paragraph metrics confirmed:',
    '- heading body-format residue cleared confirmed:',
    '- heading TOC/chapter-start sync confirmed:',
    '- formula numbering same-line confirmed:',
    '- formula numbering far-right confirmed:',
    '- abstract surfaces confirmed:',
    '- Chinese abstract title confirmed:',
    '- Chinese abstract body confirmed:',
    '- Chinese keyword line confirmed:',
    '- Chinese keyword label/content run split confirmed:',
    '- English abstract title confirmed:',
    '- English abstract body confirmed:',
    '- English keyword line confirmed:',
    '- English keyword label/content run split confirmed:',
    '- English abstract semantic parity confirmed:',
    '- cover page-class baseline confirmed:',
    '- cover identity-zone baseline confirmed:',
    '- cover identity value-line baseline confirmed:',
    '- declaration/title front matter baseline confirmed:',
    '- declaration separated from cover confirmed:',
    '- caption wording clean confirmed:',
    '- caption baseline class confirmed:',
    '- header/footer baseline confirmed:',
    '- footer/page-number presentation confirmed:',
    '- page-number structure confirmed:',
    '- table-local structure clean confirmed:',
    '- tail-block title baseline confirmed:',
    '- tail-block opener fresh-page confirmed:',
    '- tail-block separation from prior block confirmed:',
    '- tail-block singular pagination owner confirmed:',
    '- references title indentation confirmed:',
    '- references entries indentation confirmed:',
    '- acknowledgement title indentation confirmed:',
    '- acknowledgement body indentation confirmed:',
    '- end-matter rendered geometry confirmed:',
    '- structural figure geometry validation report path:',
    '- structural source-scale bbox map path:',
    '- structural inserted-scale geometry evidence path:',
    '- structural dense-zone crop evidence paths:',
    '- structural relation-attribute collision verdict:',
    '- structural shape-overlap verdict:',
    '- structural source-to-inserted geometry verdict:',
    '- structural source-scale collision report confirmed:',
    '- structural inserted-scale dense-zone review confirmed:',
]

REVIEW_EVIDENCE_RENDERER_REQUIRED_PREFIXES = [
    '- renderer executable path:',
    '- render command:',
    '- rendered PDF path:',
    '- page image path list:',
    '- logical-to-physical page mapping method:',
    '- sentinel text confirmed:',
    '- machine-vision verdict:',
]

REVIEW_EVIDENCE_RENDERER_REQUIRED_TYPES = {
    'figure-review',
    'paragraph-review',
    'thesis-rendered-page',
    'touched-page-review',
}

REVIEW_EVIDENCE_SURFACE_CONFIRM_PREFIXES = {
    'caption': [
        '- caption wording clean confirmed:',
        '- caption baseline class confirmed:',
    ],
    'formula': [
        '- formula numbering same-line confirmed:',
        '- formula numbering far-right confirmed:',
    ],
    'header_footer': [
        '- header/footer baseline confirmed:',
        '- footer/page-number presentation confirmed:',
    ],
    'table': [
        '- table authority source confirmed:',
        '- table manuscript binding confirmed:',
        '- active table family confirmed:',
        '- table-local structure clean confirmed:',
    ],
    'tail_block': [
        '- tail-block title baseline confirmed:',
        '- tail-block opener fresh-page confirmed:',
        '- tail-block separation from prior block confirmed:',
        '- tail-block singular pagination owner confirmed:',
        '- references title indentation confirmed:',
        '- references entries indentation confirmed:',
        '- acknowledgement title indentation confirmed:',
        '- acknowledgement body indentation confirmed:',
        '- end-matter rendered geometry confirmed:',
    ],
    'toc': [
        '- TOC title baseline confirmed:',
        '- TOC level formatting confirmed:',
        '- TOC dotted-leader / right-tab confirmed:',
        '- TOC page-number column confirmed:',
        '- TOC restored from locked baseline confirmed:',
        '- TOC page occupancy baseline confirmed:',
    ],
    'body_heading': [
        '- heading level baseline confirmed:',
        '- heading direct-run typography confirmed:',
        '- heading paragraph metrics confirmed:',
        '- heading body-format residue cleared confirmed:',
        '- heading TOC/chapter-start sync confirmed:',
    ],
}

REVIEW_EVIDENCE_SURFACE_DETECTOR_SPECS = {
    'abstract': {
        'tokens': (
            'abstract',
            '\u6458\u8981',
            'keyword',
            '\u5173\u952e\u8bcd',
            'front matter',
        ),
    },
    'caption': {
        'tokens': (
            'caption',
            'figure caption',
            'table caption',
            'table title',
            '\u56fe\u9898',
            '\u8868\u9898',
            '\u56fe\u6ce8',
            '\u8868\u6ce8',
        ),
    },
    'body_heading': {
        'tokens': (
            'body heading',
            'body heading levels',
            'heading levels',
            'heading family',
            'chapter heading',
            'body_heading_levels',
            '\u6b63\u6587\u6807\u9898',
            '\u6807\u9898\u5c42\u7ea7',
        ),
    },
    'formula': {
        'tokens': (
            'formula',
            'equation',
            '\u516c\u5f0f',
            '\u5f0f4-',
            '\u5f0f',
        ),
    },
    'header_footer': {
        'tokens': (
            'header',
            'footer',
            'page number',
            'header/footer',
            '\u9875\u7709',
            '\u9875\u811a',
            '\u9875\u7801',
        ),
    },
    'table': {
        'tokens': (
            'table',
            'tables',
            'table family',
            'table style',
            'three-line table',
            'WPS preset',
            '\u8868',
            '\u8868\u683c',
            '\u4e09\u7ebf\u8868',
        ),
    },
    'tail_block': {
        'tokens': (
            'tail-block',
            'tail block',
            'end matter',
            'references',
            'bibliography',
            'acknowledgement',
            'acknowledgements',
            'acknowledgment',
            'acknowledgments',
            'conclusion',
            'appendix',
            '\u53c2\u8003\u6587\u732e',
            '\u81f4\u8c22',
            '\u7ed3\u8bba',
            '\u9644\u5f55',
        ),
    },
    'toc': {
        'tokens': (
            'toc',
            'table of contents',
            '\u76ee\u5f55',
        ),
    },
}

REVIEW_EVIDENCE_SURFACE_TEXT_PREFIXES = [
    '- target surface:',
    '- target identifier:',
    '- checks performed:',
    '- summary:',
    '- sentinel text confirmed:',
]

RUNTIME_SCREENSHOT_HINT_TOKENS = (
    'runtime screenshot',
    'screenshot',
    'chapter 4',
    '\u56fe4.',
    '\u8fd0\u884c\u622a\u56fe',
)

TABLE_HINT_TOKENS = (
    'table',
    'tables',
    'table family',
    'table style',
    'three-line table',
    'WPS preset',
    '\u8868',
    '\u8868\u683c',
    '\u4e09\u7ebf\u8868',
)

TAIL_BLOCK_HINT_TOKENS = (
    'tail-block',
    'tail block',
    'end matter',
    'tail-block title indentation',
    'title indentation',
    'left indent',
    'hanging indent',
    'first-line indent',
    'rendered left-x',
    'centerline',
    'references',
    'bibliography',
    'acknowledgement',
    'acknowledgements',
    'acknowledgment',
    'acknowledgments',
    'conclusion',
    'appendix',
    '\u53c2\u8003\u6587\u732e',
    '\u81f4\u8c22',
    '\u7ed3\u8bba',
    '\u9644\u5f55',
)

TOC_HINT_TOKENS = (
    'toc',
    'table of contents',
    '\u76ee\u5f55',
)
