"""Registry constants for validate_skill_gate."""

from __future__ import annotations

__all__ = [
    'BODY_STYLE_AUDIT_SCHEMA',
    'CITATION_AUDIT_SCHEMA',
    'TEXT_EXTENSIONS',
    'TEXT_EVIDENCE_EXTENSIONS',
    'IMAGE_EXTENSIONS',
    'PDF_EXTENSIONS',
    'EXPLICIT_VALUES',
    'PLACEHOLDER_VALUES',
    'DOCX_FONT_AUDIT_SCHEMA',
    'FINAL_ACCEPTANCE_SCHEMA',
    'HUMANIZER_EVIDENCE_SCHEMA',
    'REVIEW_EVIDENCE_SCHEMA',
    'FORMAT_REPAIR_TASK_SCHEMA',
]

BODY_STYLE_AUDIT_SCHEMA = {
    'headings': [
        '# DOCX Body Style Audit',
        '## Binding Issues',
        '## Normal Baseline Issues',
        '## Body Family Issues',
        '## Heading Contamination Issues',
        '## Mixed-Script Body Issues',
        '## Direct Visible Metric Issues',
    ],
    'single_prefixes': [
        '- reference docx path:',
        '- reference docx sha256:',
        '- final docx path:',
        '- final docx sha256:',
        '- body paragraphs checked:',
        '- reference inferred body style:',
        '- final matched body style:',
        '- body style binding summary:',
        '- Normal baseline preservation summary:',
        '- body paragraph family consistency summary:',
        '- body heading contamination summary:',
        '- body mixed-script font summary:',
        '- body direct visible metrics summary:',
        '- result:',
    ],
}

CITATION_AUDIT_SCHEMA = {
    'headings': [
        '# Body Citation Audit Report',
        '## Summary',
        '## Body Citation Records',
        '## Findings',
    ],
    'single_prefixes': [
        '- document path:',
        '- document sha256:',
        '- body citation paragraph count:',
        '- unique citation count:',
        '- bibliography item count:',
        '- bibliography empty/content-missing entries:',
        '- first appearance chain:',
        '- expected chain:',
        '- missing bibliography numbers:',
        '- extra body citation numbers:',
        '- error codes:',
        '- result:',
    ],
}

TEXT_EXTENSIONS = {
    '.cmd',
    '.json',
    '.md',
    '.ps1',
    '.py',
    '.txt',
    '.yaml',
    '.yml',
}

TEXT_EVIDENCE_EXTENSIONS = {
    '.md',
    '.txt',
}

IMAGE_EXTENSIONS = {
    '.bmp',
    '.jpeg',
    '.jpg',
    '.png',
    '.tif',
    '.tiff',
    '.webp',
}

PDF_EXTENSIONS = {
    '.pdf',
}

EXPLICIT_VALUES = {
    '-',
    '[]',
    'n/a',
    'na',
    'no',
    'none',
    'not applicable',
    'not-applicable',
}

PLACEHOLDER_VALUES = {
    '',
    '?',
    'pending',
    'tbd',
    'todo',
    'unknown',
}

DOCX_FONT_AUDIT_SCHEMA = {
    'headings': [
        '# DOCX Font And Encoding Audit',
        '## Font Hits',
        '## Visible Text Hits',
        '## Generic Token Hits',
        '## Bibliography Font-Slot Hits',
    ],
    'single_prefixes': [
        '- docx path:',
        '- docx sha256:',
        '- checked parts:',
        '- suspicious font-name hits:',
        '- suspicious visible-text hits:',
        '- suspicious generic-token hits:',
        '- bibliography reference docx path:',
        '- bibliography reference docx sha256:',
        '- bibliography expected size name:',
        '- bibliography expected size half-points:',
        '- bibliography size policy source:',
        '- bibliography entry count:',
        '- bibliography checked run count:',
        '- bibliography content-format model checks:',
        '- bibliography content-format model source:',
        '- bibliography empty-entry/content completeness checks:',
        '- bibliography empty-entry/content completeness hits:',
        '- bibliography named-size WPS evidence path:',
        '- bibliography named-size WPS evidence verdict:',
        '- bibliography font-slot checks:',
        '- bibliography font-slot hits:',
        '- result:',
    ],
}

FINAL_ACCEPTANCE_SCHEMA = {
    'headings': [
        '# Final Acceptance Template',
        '## Mode',
        '## Active References And Checklists',
        '## Condition Locks',
        '## Program Checks',
        '## Thesis Checks',
        '## Figure Checks',
        '## Verification Evidence',
        '## Blockers And Skips',
        '## Remaining Risks',
        '## Validation',
    ],
    'repeated_prefix_counts': {
        '- failed:': 3,
        '- passed:': 3,
        '- skipped:': 3,
        '- acknowledgement body paragraph-dialog metrics verdict:': 2,
        '- acknowledgement body direct-run typography verdict:': 2,
        '- acknowledgement body first-line indent verdict:': 2,
        '- acknowledgement body title-contamination verdict:': 2,
    },
    'single_prefixes': [
        '- task mode:',
        '- subtask:',
        '- loaded references:',
        '- routed child files:',
        '- active checklist names:',
        '- program condition lock:',
        '- thesis lane lock:',
        '- selected thesis workflow:',
        '- thesis mutation transaction owner path:',
        '- thesis mutation transaction record path:',
        '- thesis mutation transaction workflow:',
        '- thesis mutation transaction subtype:',
        '- thesis mutation transaction target surfaces:',
        '- thesis mutation transaction protected sibling surfaces:',
        '- thesis mutation transaction write owner:',
        '- thesis mutation transaction final docx sha256:',
        '- explicit user overrides:',
        '- agent authorization source:',
        '- agent mode:',
        '- max concurrent live agents:',
        '- live agent count plan:',
        '- dispatch wave plan:',
        '- audit presence by wave:',
        '- concurrency limit verdict:',
        '- required lanes:',
        '- complete role roster:',
        '- role attendance matrix:',
        '- not-applicable lanes with reasons:',
        '- agent role aliases zh:',
        '- required lane aliases zh:',
        '- spawned agent aliases zh:',
        '- lane alias map zh:',
        '- audit role alias zh:',
        '- spawned agent ids:',
        '- audit agent id:',
        '- sequential audit fallback id:',
        '- audit spawn or fallback mode:',
        '- audit verdict:',
        '- audit verdict cadence:',
        '- handoff status:',
        '- known caveats:',
        '- baseline promotion status:',
        '- baseline promotion evidence path:',
        '- release blocker ledger path:',
        '- unresolved release blocker count:',
        '- scoped artifact next-baseline verdict:',
        '- action audit scope:',
        '- action audit verdict cadence:',
        '- action audit verdicts:',
        '- action cycles:',
        '- action categories:',
        '- action owner map:',
        '- sequential fallback reason:',
        '- skill invocation lock path:',
        '- skill invocation lock verdict:',
        '- skill invocation verified:',
        '- skill invocation source type:',
        '- skill activation status:',
        '- skill takeover verdict:',
        '- skill bypass prevention verdict:',
        '- canonical gate enforcement verdict:',
        '- narrow/smoke substitute gate used?:',
        '- blocked evidence escalation verdict:',
        '- no non-control action before lock?:',
        '- final handoff allowed by skill lock?:',
        '- routed references verified:',
        '- active checklist verified:',
        '- user request compliance verdict:',
        '- loaded rule compliance verdict:',
        '- helper-script target path lock:',
        '- helper scripts planned this round:',
        '- helper script provenance summary:',
        '- delegated canonical helper paths:',
        '- project-local helper script preflight summary:',
        '- project-local helper preflight report path:',
        '- project-local helper active run dir:',
        '- project-local helper risk count:',
        '- project-local helper scanner exit status:',
        '- project-local helper disposition:',
        '- canonical source restart required?:',
        '- source manuscript genealogy path:',
        '- source retention manifest path:',
        '- source retention ratio:',
        '- source retention verdict:',
        '- source review-artifact inventory path:',
        '- final review-artifact diff path:',
        '- controlled bookmark disposition path:',
        '- review comments/change marks preservation verdict:',
        '- comments strip explicit user approval:',
        '- comment-resolution source DOCX path:',
        '- comment-resolution source DOCX SHA256:',
        '- comment-resolution ledger path:',
        '- comment-resolution audit report path:',
        '- comment-resolution audit verdict:',
        '- source body-citation run inventory path:',
        '- final body-citation run diff path:',
        '- body citation superscripts preservation verdict:',
        '- citation-reference coupled-chain verdict:',
        '- rebuild class:',
        '- clean-source restart source path:',
        '- contaminated-baseline disposition:',
        '- project template discovery root:',
        '- template discovery patterns:',
        '- discovered candidate template paths:',
        '- candidate template selection reason:',
        '- active template source type:',
        '- active template path lock:',
        '- active template fingerprint:',
        '- active template profile path:',
        '- active template selected before mutation?:',
        '- template discovery report path:',
        '- template profile generation command:',
        '- template profile generated before mutation?:',
        '- locked path encoding verdict:',
        '- contaminated intermediate source used?:',
        '- contaminated intermediate source disposition:',
        '- template alignment verdict:',
        '- format preservation promise active?:',
        '- format preservation promise source:',
        '- format preservation promise verdict:',
        '- protected-surface ownership lock:',
        '- protected-surface evidence contract path:',
        '- protected-surface evidence contract loaded?:',
        '- canonical protected surface id set:',
        '- protected-surface owner map:',
        '- protected-surface evidence map:',
        '- protected-surface reviewed output sha256:',
        '- protected-surface evidence contract verdict:',
        '- touched template-owned surface families:',
        '- surface-face parity baseline locks:',
        '- custom/builder/default font usage allowed?:',
        '- font baseline blockers:',
        '- humanizer route decision:',
        '- humanizer target language:',
        '- humanizer scope:',
        '- verification scope claim:',
        '- agent run manifest path:',
        '- lightweight action-audit entry path:',
        '- lane task card evidence paths:',
        '- all role task card paths:',
        '- audit full roster verdict:',
        '- agent id alias map:',
        '- path format rule:',
        '- filled format-repair task record path:',
        '- protected-surface freeze manifest path:',
        '- protected-surface freeze manifest verdict:',
        '- post-mutation surface diff path:',
        '- post-mutation surface diff verdict:',
        '- target surface render review path:',
        '- target surface render review verdict:',
        '- blast-radius render review path:',
        '- blast-radius render review verdict:',
        '- cross-surface regression report path:',
        '- cross-surface regression report verdict:',
        '- non-target protected surface change verdict:',
        '- non-target format preservation verdict:',
        '- local-surface whole-thesis claim verdict:',
        '- thesis mutation transaction validator command:',
        '- thesis mutation transaction validator result:',
        '- verified renderer path:',
        '- verified rasterizer path:',
        '- review-copy path actually rendered:',
        '- rendered PDF path:',
        '- full rendered page/footer map path:',
        '- page-image artifact paths:',
        '- final DOCX whole-format structural audit path:',
        '- final DOCX whole-format structural audit verdict:',
        '- final DOCX font-color audit path:',
        '- final DOCX font-color audit verdict:',
        '- exact output paths:',
        '- sample self-check report path:',
        '- sample self-check header-footer.page-number-template-contract detector:',
        '- page-class coverage matrix evidence path:',
        '- mandatory thesis surface inventory path:',
        '- front matter surface coverage matrix path:',
        '- end matter surface coverage matrix path:',
        '- high-risk thesis format surface matrix path:',
        '- protected surface contract evidence path:',
        '- cover style evidence path:',
        '- cover style verdict:',
        '- cover identity value-line evidence path:',
        '- cover identity value-line verdict:',
        '- cover value cell targeted verdict:',
        '- cover label cell unchanged verdict:',
        '- cover underline x/y/width evidence path:',
        '- cover value text bbox evidence path:',
        '- cover value-on-underline verdict:',
        '- cover row baseline alignment verdict:',
        '- declaration/title front matter evidence path:',
        '- declaration/title front matter verdict:',
        '- Chinese abstract title evidence path:',
        '- Chinese abstract title verdict:',
        '- Chinese abstract body evidence path:',
        '- Chinese abstract body verdict:',
        '- Chinese keyword line evidence path:',
        '- Chinese keyword line verdict:',
        '- English abstract title evidence path:',
        '- English abstract title verdict:',
        '- English abstract body evidence path:',
        '- English abstract body verdict:',
        '- English keyword line evidence path:',
        '- English keyword line verdict:',
        '- TOC title evidence path:',
        '- TOC title verdict:',
        '- TOC entries evidence path:',
        '- TOC entries verdict:',
        '- TOC dotted leaders evidence path:',
        '- TOC dotted leaders verdict:',
        '- TOC page-number column evidence path:',
        '- TOC page-number column verdict:',
        '- TOC implementation family/live-field parity evidence path:',
        '- TOC implementation family/live-field parity verdict:',
        '- TOC per-level template baseline evidence path:',
        '- TOC rendered geometry comparison path:',
        '- TOC title/level font and paragraph metrics verdict:',
        '- TOC dotted leader and page-number column verdict:',
        '- TOC occupancy rhythm verdict:',
        '- body heading levels evidence path:',
        '- body heading levels verdict:',
        '- body text evidence path:',
        '- body text verdict:',
        '- body citation superscripts evidence path:',
        '- body citation superscripts verdict:',
        '- review comments/change marks evidence path:',
        '- review comments/change marks verdict:',
        '- chapter format preservation detector verdict:',
        '- chapter format diff path:',
        '- touched chapter rendered evidence paths:',
        '- references title evidence path:',
        '- references title verdict:',
        '- references entries evidence path:',
        '- rendered references-page evidence path:',
        '- references entries verdict:',
        '- acknowledgement title evidence path:',
        '- acknowledgement title verdict:',
        '- acknowledgement body evidence path:',
        '- acknowledgement body verdict:',
        '- header evidence path:',
        '- header verdict:',
        '- header presence verdict:',
        '- header rendered verdict:',
        '- header expected display string source:',
        '- header rendered full-display evidence path:',
        '- header chapter number preservation verdict:',
        '- body opener/header title consistency evidence path:',
        '- body opener/header title consistency verdict:',
        '- footer evidence path:',
        '- footer verdict:',
        '- page numbers evidence path:',
        '- page numbers verdict:',
        '- forbidden substitute evidence used?:',
        '- user-reported issue ledger path:',
        '- user-reported visual defect surfaces:',
        '- user-reported visual defect render-geometry evidence path:',
        '- user-reported visual defect template-vs-target binding verdict:',
        '- user-reported visual defect full-page/key-surface binding verdict:',
        '- content mutation rendered-page review path:',
        '- content mutation machine-vision verdict:',
        '- inserted body heading-contamination verdict:',
        '- caption/table sibling body contamination verdict:',
        '- touched-page/blast-radius machine-vision evidence paths:',
        '- format lane post-mutation rendered audit verdict:',
        '- figure asset manifest path:',
        '- figure source DOCX path:',
        '- figure source DOCX SHA256:',
        '- figure user material source path:',
        '- figure user material source SHA256:',
        '- figure material-source inventory path:',
        '- figure material-source binding verdict:',
        '- figure generated-substitute rejection verdict:',
        '- figure inventory path:',
        '- figure manifest contract verdict:',
        '- figure extents audit path:',
        '- figure paragraph-margin width verdict:',
        '- figure visible-content completeness verdict:',
        '- figure nonzero crop count:',
        '- figure exact-line-spacing clipping count:',
        '- figure image-holder layout verdict:',
        '- figure image-holder layout issue count:',
        '- per-figure rendered evidence paths:',
        '- runtime screenshot full-window geometry evidence paths:',
        '- runtime screenshot full-window capture verdict:',
        '- algorithm result authenticity evidence paths:',
        '- algorithm result source/provenance evidence paths:',
        '- algorithm result caption-to-asset map path:',
        '- algorithm result system search / startup attempt path:',
        '- algorithm result provenance verdict:',
        '- code screenshot authenticity evidence paths:',
        '- algorithm code visibility evidence path:',
        '- algorithm code visibility verdict:',
        '- TOC digits/cache preservation evidence path:',
        '- TOC digits/cache preservation verdict:',
        '- toc restoration evidence paths:',
        '- toc rendered baseline comparison evidence paths:',
        '- toc visual geometry evidence paths:',
        '- toc paragraph-and-typography evidence paths:',
        '- toc visible-run typography evidence paths:',
        '- whole-document pagination evidence path:',
        '- package baseline manifest path:',
        '- package drift report path:',
        '- package drift verdict:',
        '- pre-mutation page map path:',
        '- post-mutation page map path:',
        '- whole-document pagination diff path:',
        '- section break numbering map path:',
        '- chapter start owner map path:',
        '- tail-block owner map path:',
        '- TOC-to-heading page sync map path:',
        '- logical-physical page map path:',
        '- blank-page scan evidence path:',
        '- rendered page count baseline/actual:',
        '- field-refresh before/after state:',
        '- tail-block pagination evidence paths:',
        '- tail-block rendered opener comparison evidence paths:',
        '- table authority evidence paths:',
        '- table-local structure evidence paths:',
        '- table rendered baseline comparison evidence paths:',
        '- table title-mode evidence paths:',
        '- table header-bottom middle-rule evidence paths:',
        '- flowchart semantic trigger inventory path:',
        '- flowchart draw.io source evidence paths:',
        '- flowchart SVG export evidence paths:',
        '- flowchart raster fallback evidence paths:',
        '- flowchart source-scale geometry report paths:',
        '- flowchart rendered-page evidence paths:',
        '- flowchart final DOCX relationship evidence paths:',
        '- flowchart manifest contract verdict:',
        '- citation audit evidence path:',
        '- citation audit final DOCX SHA256:',
        '- citation audit source-to-final run diff path:',
        '- citation anchor pollution audit path:',
        '- citation anchor pollution verdict:',
        '- citation anchor visible DOCX hit count:',
        '- citation anchor field-result hit count:',
        '- citation anchor rendered PDF hit count:',
        '- citation anchor pollution final DOCX SHA256:',
        '- bibliography audit evidence path:',
        '- bibliography empty-entry/content completeness evidence path:',
        '- bibliography empty-entry/content completeness verdict:',
        '- bibliography baseline summary:',
        '- bibliography numbering summary:',
        '- bibliography comment-aware repair summary:',
        '- project-local helper script paths:',
        '- project-local helper script risk summary:',
        '- docx font/encoding audit evidence path:',
        '- per-surface mixed-script font-slot matrix path:',
        '- per-surface mixed-script font-slot verdict:',
        '- surface-face parity audit evidence path:',
        '- surface paragraph-and-typography audit evidence path:',
        '- sibling-surface audit evidence path:',
        '- cross-surface regression freeze evidence path:',
        '- font-family baseline audit evidence path:',
        '- active template profile evidence path:',
        '- body style audit evidence path:',
        '- program evidence paths:',
        '- thesis rendered-page evidence paths:',
        '- figure review evidence paths:',
        '- paragraph-review evidence paths:',
        '- touched-page review evidence paths:',
        '- machine-vision summary by touched surface:',
        '- startup / runtime verification summary:',
        '- thesis rendered-page verification summary:',
        '- action-level audit summary:',
        '- post-script smoke-audit summary:',
        '- body style binding summary:',
        '- Normal baseline preservation summary:',
        '- body paragraph family consistency summary:',
        '- surface-face parity summary:',
        '- surface paragraph-and-typography summary:',
        '- surface paragraph-and-typography verdict:',
        '- sibling-surface audit summary:',
        '- style-blast-radius escalation summary:',
        '- cross-surface regression verdict:',
        '- TOC underline pollution verdict:',
        '- table style regression verdict:',
        '- font-family baseline summary:',
        '- builder/default font rejection summary:',
        '- code title formatting summary:',
        '- code block formatting summary:',
        '- abstract baseline preservation summary:',
        '- abstract and keyword surface verdict:',
        '- keyword content title-style contamination evidence path:',
        '- keyword content title-style contamination verdict:',
        '- heading baseline preservation summary:',
        '- heading family preservation summary:',
        '- heading level 1 verdict:',
        '- heading level 2 verdict:',
        '- heading level 3 verdict:',
        '- heading level 4 verdict:',
        '- heading direct rPr/font/size/bold/spacing verdict:',
        '- TOC / bookmark integrity summary:',
        '- TOC visible format summary:',
        '- TOC baseline restoration summary:',
        '- TOC visual rhythm summary:',
        '- TOC visual baseline verdict:',
        '- TOC visual geometry verdict:',
        '- TOC paragraph-and-typography verdict:',
        '- TOC visible-run typography verdict:',
        '- table authority summary:',
        '- table-local structure summary:',
        '- table title-mode summary:',
        '- table header-bottom middle-rule summary:',
        '- table donor title mode:',
        '- table target title mode:',
        '- table title-mode verdict:',
        '- table in-table merged-title-row verdict:',
        '- table top rule verdict:',
        '- table header separator rule verdict:',
        '- table body middle-rule policy verdict:',
        '- table bottom rule verdict:',
        '- table rendered crop metric json path:',
        '- chapter-start pagination summary:',
        '- tail-block pagination summary:',
        '- whole-document pagination summary:',
        '- whole-document pagination verdict:',
        '- custom-layout result-table preservation summary:',
        '- figure family style summary:',
        '- figure source/style contract summary:',
        '- exact final CAD delivery package path:',
        '- exact final CAD delivery package sha256:',
        '- exact DWG package path:',
        '- exact DWG package sha256:',
        '- exact combined drawing PDF path:',
        '- exact combined drawing PDF sha256:',
        '- mechanical drawing package audit path:',
        '- mechanical drawing package audit verdict:',
        '- mechanical drawing formal CAD source provenance verdict:',
        '- mechanical drawing schematic/concept substitute rejection verdict:',
        '- CAD official command route verdict:',
        '- CAD official command test log:',
        '- CAD executable or COM ProgID evidence:',
        '- non-CAD fallback rejection verdict:',
        '- external CAD case reference URL:',
        '- reference-use restriction:',
        '- no verbatim geometry copying verdict:',
        '- mechanical drawing reference baseline path:',
        '- mechanical drawing CAD open-view close-up evidence path:',
        '- mechanical drawing CAD open-view structural coherence verdict:',
        '- mechanical drawing complete assembly/object recognizability verdict:',
        '- mechanical drawing scattered-parts rejection verdict:',
        '- mechanical drawing reference-view trace alignment verdict:',
        '- mechanical drawing annotation/leader/title-block completeness verdict:',
        '- mechanical drawing external-case annotation checklist path:',
        '- mechanical drawing package exact package path:',
        '- mechanical drawing package exact package sha256:',
        '- mechanical drawing rendered review evidence paths:',
        '- mechanical drawing rendered no-overlap verdict:',
        '- mechanical drawing boundary clearance verdict:',
        '- mechanical drawing detail density verdict:',
        '- mechanical drawing title block/table/notes isolation verdict:',
        '- mechanical drawing title-block cell containment verdict:',
        '- mechanical drawing annotation margin clearance verdict:',
        '- mechanical drawing local crowding verdict:',
        '- mechanical drawing text/table/frame overlap verdict:',
        '- mechanical render readability audit path:',
        '- mechanical render readability verdict:',
        '- mechanical render readability source lineweight verdict:',
        '- mechanical render readability render-only stroke cap:',
        '- mechanical render readability render-only lineweight scaling:',
        '- text text overlap count:',
        '- text graphic cover count:',
        '- severe line crowding count:',
        '- mechanical render readability small-tile threshold:',
        '- mechanical render readability failed sheet list:',
        '- mechanical render readability requires crop review count:',
        '- mechanical render readability line bundle blocker count:',
        '- mechanical render readability diagnostic-overlay-free crop review path:',
        '- mechanical render readability standard-sheet view occupancy verdict:',
        '- mechanical render readability final PDF/PNG SHA evidence:',
        '- mechanical drawing machine overlap audit verdict:',
        '- mechanical drawing content-overlap audit verdict:',
        '- mechanical drawing content-overlap evidence path:',
        '- mechanical drawing registered content bbox count:',
        '- mechanical drawing checked content pair count:',
        '- mechanical drawing content overlap count:',
        '- mechanical drawing view-view overlap count:',
        '- mechanical drawing detail-frame-main-view overlap count:',
        '- mechanical drawing table text/grid collision count:',
        '- mechanical drawing dimension-line view/table crossing count:',
        '- mechanical drawing leader-line view/table crossing count:',
        '- mechanical drawing balloon geometry collision count:',
        '- mechanical drawing bbox helper envelope escape count:',
        '- mechanical drawing stale rendered preview count:',
        '- mechanical drawing outside-frame ink audit verdict:',
        '- mechanical drawing outside-frame ink audit evidence path:',
        '- mechanical drawing outside-frame independent ink component count:',
        '- mechanical drawing outside-frame text component count:',
        '- mechanical drawing outside-frame leader component count:',
        '- mechanical drawing outside-frame hatch/section component count:',
        '- mechanical drawing outside-frame table/title-block component count:',
        '- mechanical drawing inner-frame safe-margin audit verdict:',
        '- mechanical drawing inner-frame safe-margin evidence path:',
        '- mechanical drawing right safe-boundary intrusion count:',
        '- mechanical drawing leader-text inner-frame intrusion count:',
        '- mechanical drawing view-geometry inner-frame intrusion count:',
        '- mechanical drawing dimension-text inner-frame intrusion count:',
        '- mechanical drawing annotation ownership audit verdict:',
        '- mechanical drawing unowned free text count:',
        '- mechanical drawing unsupported floating text count:',
        '- mechanical drawing reserved-zone intrusion audit verdict:',
        '- mechanical drawing reserved-zone intrusion count:',
        '- mechanical drawing dimension-line table-zone intrusion count:',
        '- mechanical drawing dimension-text table-zone intrusion count:',
        '- mechanical drawing view-geometry reserved-zone intrusion count:',
        '- mechanical drawing hatch/section fill clipping audit verdict:',
        '- mechanical drawing hatch/section fill clipping evidence path:',
        '- mechanical drawing hatch/section fill boundary violation count:',
        '- mechanical drawing hatch/section fill adjacent-view crossing count:',
        '- mechanical drawing hatch/section fill dimension-line crossing count:',
        '- mechanical drawing hatch/section fill title-block/table/BOM/frame crossing count:',
        '- mechanical drawing hatch/section fill blank-background leak count:',
        '- mechanical drawing text entity overlap count:',
        '- mechanical drawing text legibility machine audit verdict:',
        '- mechanical drawing minimum CAD text height mm:',
        '- mechanical drawing minimum rendered text height px:',
        '- mechanical drawing text integrity audit path:',
        '- mechanical drawing text integrity audit verdict:',
        '- mechanical drawing mojibake/tofu/missing glyph count:',
        '- mechanical drawing missing required drawing text count:',
        '- mechanical drawing text orientation audit path:',
        '- mechanical drawing text orientation audit verdict:',
        '- mechanical drawing upside-down text count:',
        '- mechanical drawing mirrored text count:',
        '- mechanical drawing lineweight/linetype fidelity audit path:',
        '- mechanical drawing lineweight/linetype fidelity audit verdict:',
        '- mechanical drawing lineweight/linetype fidelity package sha256:',
        '- mechanical drawing color-family audit path:',
        '- mechanical drawing color-family audit verdict:',
        '- mechanical drawing color-family package/path sha256:',
        '- mechanical drawing thin-solid-white-only verdict:',
        '- mechanical drawing non-thin white layer/entity count:',
        '- mechanical drawing expected color family count:',
        '- mechanical drawing entity color override count:',
        '- mechanical drawing source line family coverage verdict:',
        '- mechanical drawing PDF page-box sheet-size audit verdict:',
        '- mechanical drawing rendered ink contrast audit verdict:',
        '- mechanical drawing worst readable ink ratio:',
        '- mechanical drawing minimum readable ink ratio:',
        '- mechanical drawing effective DWG byte-density ratio:',
        '- mechanical drawing estimated PDF sheet workload:',
        '- mechanical drawing A-series page box count:',
        '- mechanical drawing thick solid family count:',
        '- mechanical drawing thin solid family count:',
        '- mechanical drawing center dash-dot family count:',
        '- mechanical drawing hidden dashed family count:',
        '- mechanical drawing section hatch family count:',
        '- mechanical drawing manufacturing complexity audit verdict:',
        '- mechanical drawing minimum manufacturing detail family count:',
        '- mechanical drawing entity-count-only false-pass verdict:',
        '- CAD appendix binding audit path:',
        '- CAD appendix binding audit verdict:',
        '- CAD appendix matched sheet count:',
        '- CAD appendix missing sheet count:',
        '- CAD appendix final DOCX SHA256:',
        '- CAD appendix final package path:',
        '- table rendered-family summary:',
        '- WPS preset application summary:',
        '- image replacement rendered summary:',
        '- image metadata sync summary:',
        '- formula object audit evidence path:',
        '- formula number layout issue count:',
        '- formula rendered label geometry path:',
        '- formula rendered label split count:',
        '- formula rendered label font-size verdict:',
        '- formula narrative-context verdict:',
        '- formula dump marker count:',
        '- formula without nearby body explanation count:',
        '- formula narrative style issue count:',
        '- orphan formula style issue count:',
        '- formula duplicate-density verdict:',
        '- unique formula ratio:',
        '- duplicate formula body text count:',
        '- formula object preservation summary:',
        '- formula numbering surface summary:',
        '- header placement summary:',
        '- footer indent summary:',
        '- footer baseline typography summary:',
        '- references entry format verdict:',
        '- bibliography label-family decision path:',
        '- reference rendered label geometry path:',
        '- appendix format verdict:',
        '- high-risk thesis format surface verdict:',
        '- humanizer evidence path:',
        '- humanizer manual or skill run id:',
        '- humanizer processed paragraph count:',
        '- humanizer changed pattern list:',
        '- humanizer no meta-evaluation voice verdict:',
        '- blockers:',
        '- skipped with reasons:',
        '- failed with reasons:',
        '- acceptance record path:',
        '- skill selftest command:',
        '- skill selftest result:',
        '- validation command:',
        '- validation result:',
    ],
    'template_only_headings': [
        '## Handoff Rule',
    ],
}

HUMANIZER_EVIDENCE_SCHEMA = {
    'headings': [
        '# Humanizer Evidence Template',
        '## Humanizer Evidence Record',
        '## Required Fields',
    ],
    'single_prefixes': [
        '- evidence id:',
        '- target language:',
        '- skill name:',
        '- skill file path:',
        '- skill loaded before rewrite?:',
        '- route application method:',
        '- paragraph id:',
        '- before text:',
        '- after text:',
        '- rewrite changed?:',
        '- preservation verdict:',
        '- AI-pattern cleanup verdict:',
        '- blocker summary:',
    ],
}

REVIEW_EVIDENCE_SCHEMA = {
    'headings': [
        '## Review Evidence Record',
        '## Evidence Meta',
        '## Target',
        '## Blast Radius',
        '## Baseline Comparison',
        '## Checks',
        '## Notes',
    ],
    'single_prefixes': [
        '- evidence type:',
        '- task mode:',
        '- protected-surface evidence contract path:',
        '- reviewed output path:',
        '- reviewed output sha256:',
        '- evidence created after mutation?:',
        '- artifact path:',
        '- source review-artifact inventory path:',
        '- source review-artifact inventory sha256:',
        '- final review-artifact diff path:',
        '- final review-artifact diff sha256:',
        '- review comments/change marks preservation verdict:',
        '- comments strip explicit user approval:',
        '- source body-citation run inventory path:',
        '- source body-citation run inventory sha256:',
        '- final body-citation run diff path:',
        '- final body-citation run diff sha256:',
        '- body citation superscripts preservation verdict:',
        '- citation audit final DOCX SHA256:',
        '- citation audit source-to-final run diff path:',
        '- renderer executable path:',
        '- render command:',
        '- rendered PDF path:',
        '- page image path list:',
        '- target surface:',
        '- target identifier:',
        '- canonical protected surface id:',
        '- target pages or region:',
        '- logical-to-physical page mapping method:',
        '- sentinel text confirmed:',
        '- blast-radius pages:',
        '- neighboring surfaces checked:',
        '- baseline source path and sha256:',
        '- baseline surface id:',
        '- protected surface owner lane:',
        '- protected surface audit lane:',
        '- baseline paragraph/run path:',
        '- baseline metrics:',
        '- actual paragraph/run path:',
        '- actual metrics:',
        '- surface style binding baseline/actual:',
        '- surface WPS/Word paragraph-dialog metrics baseline/actual:',
        '- surface typography baseline/actual:',
        '- surface paragraph spacing baseline/actual:',
        '- surface line-spacing mode/value baseline/actual:',
        '- surface indentation chars/points baseline/actual:',
        '- surface tab stop leader baseline/actual:',
        '- surface keep/list/page-break baseline/actual:',
        '- surface scale/compression verdict:',
        '- surface paragraph-and-typography verdict:',
        '- baseline effective font chain:',
        '- actual effective font chain:',
        '- effective font slots compared:',
        '- theme/default font alias verdict:',
        '- WPS/Word UI font display evidence:',
        '- effective font-chain verdict:',
        '- rendered region image path:',
        '- template rendered region image path:',
        '- actual rendered region image path:',
        '- surface geometry comparison method:',
        '- surface page index baseline/actual:',
        '- surface crop bbox baseline/actual:',
        '- surface content bbox baseline/actual:',
        '- surface nonwhite ratio baseline/actual:',
        '- surface blank crop verdict:',
        '- surface binding method:',
        '- surface bbox baseline/actual:',
        '- surface position baseline/actual:',
        '- surface size baseline/actual:',
        '- surface line-height y-delta baseline/actual:',
        '- surface spacing before/after baseline/actual:',
        '- surface indentation/tab baseline/actual:',
        '- surface page occupancy baseline/actual:',
        '- surface geometry verdict:',
        '- package baseline manifest path:',
        '- package drift report path:',
        '- package drift verdict:',
        '- pre-mutation page map path:',
        '- post-mutation page map path:',
        '- whole-document pagination diff path:',
        '- DOCX pagination structure schema:',
        '- DOCX pagination structure generator:',
        '- DOCX pagination structure evidence path:',
        '- DOCX pagination structure verdict:',
        '- section count baseline/actual:',
        '- header/footer reference map baseline/actual:',
        '- header/footer link-to-previous inferred map baseline/actual:',
        '- section boundary map baseline/actual:',
        '- section property map baseline/actual:',
        '- page-number format/restart map baseline/actual:',
        '- header/footer link-to-previous map baseline/actual:',
        '- hard page-break / section-break map baseline/actual:',
        '- fatal pagination topology differences:',
        '- allowed content-growth pagination differences:',
        '- all pagination topology differences:',
        '- section count verdict:',
        '- header/footer reference verdict:',
        '- page-number restart verdict:',
        '- field-refresh before/after state:',
        '- TOC-to-heading page sync map:',
        '- logical-to-physical page map:',
        '- rendered page count baseline/actual:',
        '- blank/near-empty page scan verdict:',
        '- chapter opener page map:',
        '- tail-block opener page map:',
        '- page-class occupancy rhythm verdict:',
        '- whole-document pagination verdict:',
        '- TOC template rendered page/region image path:',
        '- TOC actual rendered page/region image path:',
        '- TOC visual comparison method:',
        '- TOC title bbox baseline/actual:',
        '- TOC first-entry bbox baseline/actual:',
        '- TOC row bbox map:',
        '- TOC per-level left-indent x baseline/actual:',
        '- TOC line-spacing y-delta baseline/actual:',
        '- TOC dotted-leader start/end/density baseline/actual:',
        '- TOC page-number x column baseline/actual:',
        '- TOC row count per page baseline/actual:',
        '- TOC title-to-first-entry gap baseline/actual:',
        '- TOC page occupancy rhythm baseline/actual:',
        '- TOC visual geometry verdict:',
        '- TOC style binding baseline/actual:',
        '- TOC WPS paragraph-dialog metrics baseline/actual:',
        '- TOC title typography baseline/actual:',
        '- TOC per-level typography baseline/actual:',
        '- TOC per-level paragraph spacing baseline/actual:',
        '- TOC per-level line-spacing mode/value baseline/actual:',
        '- TOC per-level indentation chars/points baseline/actual:',
        '- TOC per-level tab stop leader baseline/actual:',
        '- TOC visible run typography baseline/actual:',
        '- TOC per-level visible run typography baseline/actual:',
        '- TOC page-number run typography baseline/actual:',
        '- TOC tab/leader run typography baseline/actual:',
        '- TOC run typography verdict:',
        '- TOC scale/compression verdict:',
        '- TOC paragraph-and-typography verdict:',
        '- TOC used-level inventory:',
        '- TOC used-level evidence map:',
        '- metric-by-metric comparison verdict:',
        '- forbidden substitute evidence used?:',
        '- structural figure geometry validation report path:',
        '- structural source-scale bbox map path:',
        '- structural inserted-scale geometry evidence path:',
        '- structural inserted-scale collision evidence path:',
        '- structural dense-zone crop evidence paths:',
        '- structural relation-attribute collision verdict:',
        '- structural shape-overlap verdict:',
        '- structural inserted-scale collision verdict:',
        '- structural source-to-inserted geometry verdict:',
        '- checks performed:',
        '- machine-vision verdict:',
        '- TOC title baseline confirmed:',
        '- TOC level formatting confirmed:',
        '- TOC dotted-leader / right-tab confirmed:',
        '- TOC page-number column confirmed:',
        '- TOC restored from locked baseline confirmed:',
        '- TOC page occupancy baseline confirmed:',
        '- TOC title paragraph confirmed:',
        '- TOC entries by level confirmed:',
        '- TOC dotted leaders confirmed:',
        '- TOC page-number column per entry confirmed:',
        '- heading level baseline confirmed:',
        '- heading direct-run typography confirmed:',
        '- heading paragraph metrics confirmed:',
        '- heading body-format residue cleared confirmed:',
        '- heading TOC/chapter-start sync confirmed:',
        '- references title indentation confirmed:',
        '- references entries indentation confirmed:',
        '- acknowledgement title indentation confirmed:',
        '- acknowledgement body indentation confirmed:',
        '- end-matter rendered geometry confirmed:',
        '- table authority source confirmed:',
        '- table manuscript binding confirmed:',
        '- active table family confirmed:',
        '- table-local structure clean confirmed:',
        '- formula numbering same-line confirmed:',
        '- formula numbering far-right confirmed:',
        '- abstract surfaces confirmed:',
        '- Chinese abstract title confirmed:',
        '- Chinese abstract body confirmed:',
        '- Chinese keyword line confirmed:',
        '- Chinese keyword label/content run split confirmed:',
        '- English abstract title confirmed:',
        '- English abstract body confirmed:',
        '- English keyword line confirmed:',
        '- English keyword label/content run split confirmed:',
        '- English abstract semantic parity confirmed:',
        '- cover page-class baseline confirmed:',
        '- cover identity-zone baseline confirmed:',
        '- cover identity value-line baseline confirmed:',
        '- declaration/title front matter baseline confirmed:',
        '- declaration separated from cover confirmed:',
        '- caption wording clean confirmed:',
        '- caption baseline class confirmed:',
        '- header/footer baseline confirmed:',
        '- footer/page-number presentation confirmed:',
        '- page-number structure confirmed:',
        '- tail-block title baseline confirmed:',
        '- tail-block opener fresh-page confirmed:',
        '- tail-block separation from prior block confirmed:',
        '- tail-block singular pagination owner confirmed:',
        '- structural source-scale collision report confirmed:',
        '- structural inserted-scale dense-zone review confirmed:',
        '- result:',
        '- blocker:',
        '- summary:',
    ],
}

FORMAT_REPAIR_TASK_SCHEMA = {
    'headings': [
        '## Scope Lock',
        '## Workflow Locks',
        '## Review Evidence Paths',
        '## Baseline Source',
        '## Repair Sequence',
        '## Acceptance Focus',
    ],
    'single_prefixes': [
        '- task mode:',
        '- content frozen?:',
        '- protected blocks:',
        '- touched blocks this round:',
        '- active references:',
        '- routed child files:',
        '- active checklist names:',
        '- thesis mutation transaction owner path:',
        '- selected mutation transaction workflow:',
        '- mutation transaction subtype:',
        '- thesis mutation transaction record path:',
        '- transaction target surface ids:',
        '- transaction protected sibling surface ids:',
        '- transaction write owner:',
        '- transaction audit owner or fallback:',
        '- transaction source manuscript path:',
        '- transaction source manuscript sha256:',
        '- transaction template path:',
        '- transaction template sha256:',
        '- transaction review-copy path:',
        '- transaction review-copy sha256 before mutation:',
        '- transaction final docx path:',
        '- transaction final docx sha256:',
        '- protected-surface evidence contract path:',
        '- protected-surface evidence contract loaded?:',
        '- canonical protected surface id set:',
        '- protected-surface owner map:',
        '- protected-surface evidence map:',
        '- protected-surface reviewed output sha256:',
        '- protected-surface evidence contract verdict:',
        '- exact master manuscript path:',
        '- true current master manuscript:',
        '- exact review-copy path:',
        '- exact review-copy sha256 before mutation:',
        '- exact helper-script target path:',
        '- expected output path after helper script:',
        '- expected output sha256 after helper script:',
        '- helper scripts planned this round:',
        '- project-local helper script preflight summary:',
        '- project-local helper preflight report path:',
        '- project-local helper active run dir:',
        '- project-local helper risk count:',
        '- project-local helper scanner exit status:',
        '- project-local helper disposition:',
        '- canonical source restart required?:',
        '- source manuscript genealogy path:',
        '- source retention manifest path:',
        '- source retention ratio:',
        '- source retention verdict:',
        '- source review-artifact inventory path:',
        '- final review-artifact diff path:',
        '- review comments/change marks preservation verdict:',
        '- comments strip explicit user approval:',
        '- source body-citation run inventory path:',
        '- final body-citation run diff path:',
        '- body citation superscripts preservation verdict:',
        '- rebuild class:',
        '- clean-source restart source path:',
        '- contaminated-baseline disposition:',
        '- project template discovery root:',
        '- template discovery patterns:',
        '- discovered candidate template paths:',
        '- candidate template selection reason:',
        '- active template source type:',
        '- active template path lock:',
        '- active template fingerprint:',
        '- active template profile path:',
        '- active template selected before mutation?:',
        '- template discovery report path:',
        '- template profile generation command:',
        '- template profile generated before mutation?:',
        '- locked path encoding verdict:',
        '- contaminated intermediate source used?:',
        '- contaminated intermediate source disposition:',
        '- format preservation promise active?:',
        '- format preservation promise source:',
        '- format preservation promise verdict:',
        '- protected-surface write-owner map:',
        '- touched-surface page map:',
        '- stale audit map:',
        '- rerender target map:',
        '- mandatory thesis surface inventory path:',
        '- thesis surface inventory status matrix:',
        '- front matter surface coverage matrix path:',
        '- end matter surface coverage matrix path:',
        '- high-risk thesis format surfaces required:',
        '- high-risk thesis format surface matrix path:',
        '- mandatory surface rows required:',
        '- surfaces explicitly excluded from generic scripts:',
        '- custom-layout result tables locked this round:',
        '- active table authority lock:',
        '- table authority source type:',
        '- table authority source file path:',
        '- table authority manuscript binding proof:',
        '- table authority rationale:',
        '- WPS table preset target:',
        '- heading / TOC / chapter-start linked lane active?:',
        '- TOC repair included this round?:',
        '- TOC baseline-source lock:',
        '- TOC baseline source file path:',
        '- TOC implementation type in baseline source:',
        '- TOC restoration source allowed to be current working draft?:',
        '- TOC title visual metrics baseline:',
        '- TOC level-1 visual metrics baseline:',
        '- TOC level-2 visual metrics baseline:',
        '- TOC level-3 visual metrics baseline:',
        '- TOC title paragraph-dialog / typography metrics baseline:',
        '- TOC level-1 paragraph-dialog / typography metrics baseline:',
        '- TOC level-2 paragraph-dialog / typography metrics baseline:',
        '- TOC level-3 paragraph-dialog / typography metrics baseline:',
        '- TOC visible-run direct typography baseline:',
        '- TOC per-level text/tab/page-number run typography baseline:',
        '- TOC per-level style-binding baseline:',
        '- TOC scale/compression baseline verdict:',
        '- TOC page-count / occupancy baseline:',
        '- TOC visual geometry baseline:',
        '- TOC post-refresh restoration owner:',
        '- live TOC required this round?:',
        '- front-matter numbering convention expected on rendered pages:',
        '- office-app path used to verify adjusted page numbers:',
        '- abstract surfaces locked:',
        '- abstract baseline source file path:',
        '- Chinese abstract title baseline paragraph/run path:',
        '- Chinese abstract body baseline paragraph/run path:',
        '- Chinese keyword line baseline paragraph/run path:',
        '- English abstract title baseline paragraph/run path:',
        '- English abstract body baseline paragraph/run path:',
        '- English keyword line baseline paragraph/run path:',
        '- keyword label/content run-split baseline:',
        '- English abstract semantic parity baseline:',
        '- protected abstract/TOC evidence id rule:',
        '- template-owned surface families touched or user-reported:',
        '- style-blast-radius trigger:',
        '- protected-surface freeze manifest path:',
        '- protected_surface_freeze_manifest schema:',
        '- protected_surface_freeze_manifest sha256:',
        '- protected_surface_freeze_manifest verdict:',
        '- pre-mutation protected-surface snapshot path:',
        '- post-mutation protected-surface snapshot path:',
        '- post_mutation_surface_diff path:',
        '- post_mutation_surface_diff sha256:',
        '- post_mutation_surface_diff verdict:',
        '- target_surface_render_review path:',
        '- target_surface_render_review sha256:',
        '- target_surface_render_review verdict:',
        '- blast_radius_render_review path:',
        '- blast_radius_render_review sha256:',
        '- blast_radius_render_review verdict:',
        '- cross_surface_regression_report path:',
        '- cross_surface_regression_report sha256:',
        '- cross_surface_regression_report verdict:',
        '- non-target protected surface change verdict:',
        '- chapter_format_preservation_report path:',
        '- chapter_format_preservation_report sha256:',
        '- chapter_format_preservation_report verdict:',
        '- chapter format preservation detector verdict:',
        '- non-target format preservation verdict:',
        '- local-surface whole-thesis claim verdict:',
        '- cross-surface regression diff path:',
        '- cross-surface regression owner:',
        '- TOC underline pollution detector required?:',
        '- table style regression detector required?:',
        '- surface-face parity baseline source paths:',
        '- surface-face parity owner map:',
        '- surface-face sibling audit scope:',
        '- all-surface paragraph-dialog / typography metrics baseline:',
        '- all-surface style-binding hard-field rule:',
        '- all-surface paragraph-dialog / typography evidence record paths:',
        '- whole-document pagination surface active?:',
        '- whole-document pagination baseline source:',
        '- package baseline manifest path:',
        '- pre-mutation page map path:',
        '- section break numbering baseline path:',
        '- page-number restart baseline path:',
        '- header/footer link-to-previous baseline path:',
        '- hard page-break / section-break baseline path:',
        '- field-refresh baseline state:',
        '- TOC-to-heading page sync baseline path:',
        '- logical-physical page map baseline path:',
        '- rendered page count baseline:',
        '- blank-page scan baseline path:',
        '- cover style baseline source:',
        '- cover identity value-line baseline source:',
        '- reference-entry baseline source:',
        '- appendix baseline source or absence reason:',
        '- custom/builder/default font usage allowed?:',
        '- font baseline source for each touched surface:',
        '- Chinese/East Asian font mapping baseline:',
        '- Western/English font mapping baseline:',
        '- complex-script font mapping baseline:',
        '- effective font chain baseline required?:',
        '- protected-surface effective font chain rule:',
        '- theme/default font alias policy:',
        '- missing font or surface baseline blockers:',
        '- caption baseline source file path:',
        '- caption wording lock:',
        '- paragraph-level rendered review path:',
        '- verified renderer executable path:',
        '- verified rasterizer executable path:',
        '- touched header/footer surfaces:',
        '- body-header ownership strategy:',
        '- tail-block ownership strategy:',
        '- tail-block pagination repair included this round?:',
        '- tail-block titles in scope:',
        '- tail-block title baseline source file path:',
        '- references title baseline paragraph/run path:',
        '- references entries baseline paragraph/run path:',
        '- acknowledgement title baseline paragraph/run path:',
        '- acknowledgement body baseline paragraph/run path:',
        '- end-matter indentation detector required?:',
        '- tail-block opener ownership baseline:',
        '- tail-block pagination restoration owner:',
        '- tail-block opener page-occupancy baseline:',
        '- footer baseline source file path:',
        '- footer/page-number presentation target:',
        '- logical-page to physical-rendered-page mapping method:',
        '- post-script smoke-audit rule active?:',
        '- rendered page review evidence record paths:',
        '- thesis mutation transaction validator command:',
        '- thesis mutation transaction validator result:',
        '- paragraph-review evidence record paths:',
        '- touched-page review evidence record paths:',
        '- table-local structure evidence record paths:',
        '- rendered table baseline comparison evidence record paths:',
        '- table title-mode evidence paths:',
        '- table header-bottom middle-rule evidence paths:',
        '- chapter format diff path:',
        '- touched chapter rendered evidence paths:',
        '- TOC post-refresh restoration evidence record paths:',
        '- TOC rendered baseline comparison evidence record paths:',
        '- TOC visual geometry evidence record paths:',
        '- TOC paragraph-and-typography evidence record paths:',
        '- TOC visible-run typography evidence record paths:',
        '- whole-document pagination evidence record path:',
        '- package drift report path:',
        '- post-mutation page map path:',
        '- whole-document pagination diff path:',
        '- section break numbering map path:',
        '- chapter start owner map path:',
        '- tail-block owner map path:',
        '- TOC-to-heading page sync map path:',
        '- logical-physical page map path:',
        '- blank-page scan evidence path:',
        '- cross-surface regression freeze evidence path:',
        '- TOC underline pollution evidence path:',
        '- table style regression evidence path:',
        '- citation audit report path:',
        '- citation audit final DOCX SHA256:',
        '- citation audit source-to-final run diff path:',
        '- caption rendered review evidence record paths:',
        '- header/footer rendered review evidence record paths:',
        '- references title indentation evidence record path:',
        '- references entries indentation evidence record path:',
        '- acknowledgement title indentation evidence record path:',
        '- acknowledgement body indentation evidence record path:',
        '- rendered PDF path:',
        '- page-image artifact paths:',
        '- output manuscript paths:',
        '- reviewed output sha256:',
        '- post-script smoke-audit evidence path:',
        '- school template:',
        '- approved sample:',
        '- explicit user rule:',
        '- page-class sample comparison targets:',
        '- active table authority source summary:',
        '- TOC title baseline paragraph path:',
        '- TOC level-1 baseline paragraph path:',
        '- TOC level-2 baseline paragraph path:',
        '- TOC level-3 baseline paragraph path:',
        '- TOC level-4 baseline paragraph path:',
        '- TOC entries by used level baseline:',
        '- TOC right-tab position baseline:',
        '- TOC line-spacing baseline:',
        '- TOC paragraph before/after spacing baseline:',
        '- TOC line-spacing mode/value baseline:',
        '- TOC indentation chars/points baseline:',
        '- TOC per-level font-size/weight baseline:',
        '- TOC dotted-leader baseline:',
        '- TOC page-number column per-entry baseline:',
        '- TOC title bbox baseline:',
        '- TOC entry row bbox baseline:',
        '- TOC per-level left-indent x baseline:',
        '- TOC line-spacing y-delta baseline:',
        '- TOC dotted-leader start/end/density baseline:',
        '- TOC page-number x column baseline:',
        '- TOC row-count / page-occupancy rhythm baseline:',
        '- forbidden substitute evidence allowed?:',
        '- tail-block title baseline paragraph paths:',
        '- references title indentation baseline:',
        '- references entries left/hanging indentation baseline:',
        '- acknowledgement title indentation baseline:',
        '- acknowledgement body indentation baseline:',
        '- surface-face baseline paragraph/run paths:',
        '- surface-face baseline metrics recorded:',
        '- effective font resolver inputs:',
        '- rendered pages to inspect:',
        '- rendered sentinel texts to confirm:',
        '- specific format classes to verify:',
        '- table authority checkpoints:',
        '- table-local structure checkpoints:',
        '- surface-face parity checkpoints:',
        '- all-surface paragraph-dialog and typography checkpoints:',
        '- template alignment verdict:',
        '- mandatory thesis surface inventory checkpoints:',
        '- high-risk thesis format surface checkpoints:',
        '- high-risk omission blocker verdict:',
        '- cover style checkpoints:',
        '- cover identity value-line checkpoints:',
        '- abstract and keyword checkpoints:',
        '- abstract six-surface evidence checkpoints:',
        '- keyword label/content run-split checkpoints:',
        '- English abstract semantic parity checkpoints:',
        '- TOC visual baseline checkpoints:',
        '- TOC per-level evidence checkpoints:',
        '- TOC used-level inventory checkpoints:',
        '- TOC per-entry page-number checkpoints:',
        '- TOC visual geometry checkpoints:',
        '- TOC paragraph-dialog and typography checkpoints:',
        '- TOC visible-run text/tab/page-number typography checkpoints:',
        '- TOC visible-run typography verdict:',
        '- cross-surface regression verdict:',
        '- TOC underline pollution verdict:',
        '- table style regression verdict:',
        '- references entry format checkpoints:',
        '- references title indentation checkpoints:',
        '- references entries indentation checkpoints:',
        '- acknowledgement title indentation checkpoints:',
        '- acknowledgement body indentation checkpoints:',
        '- end-matter rendered geometry checkpoints:',
        '- appendix format checkpoints:',
        '- sibling-surface audit checkpoints:',
        '- font-family baseline checkpoints:',
        '- protected-surface effective font chain checkpoints:',
        '- builder/default font rejection checkpoints:',
        '- TOC restoration checkpoints:',
        '- post-script smoke-audit checkpoints:',
        '- chapter-start pagination checkpoints:',
        '- chapter format preservation checkpoints:',
        '- tail-block pagination checkpoints:',
        '- whole-document pagination checkpoints:',
        '- whole-document pagination verdict:',
        '- runtime screenshot route-caption-asset map path:',
        '- review-copy promotion gate:',
        '- baseline promotion gate:',
        '- release blocker ledger path:',
        '- unresolved release blocker count:',
        '- scoped artifact next-baseline verdict:',
        '- blocker conditions:',
        '- format preservation blocker conditions:',
        '- known caveats:',
        '- TOC post-refresh restoration evidence record paths:',
        '- TOC rendered baseline comparison evidence record paths:',
        '- TOC visual geometry evidence record paths:',
        '- TOC paragraph-and-typography evidence record paths:',
        '- TOC visible-run typography evidence record paths:',
        '- whole-document pagination evidence record path:',
        '- tail-block pagination evidence record paths:',
        '- tail-block rendered opener comparison evidence record paths:',
    ],
}
